import { useAuth } from "@clerk/expo";
import type { EmployeeAccessRequestStatus, EmployeeCapability } from "@harborline/contracts";
import { employeeCapabilities } from "@harborline/contracts";
import { useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Card, Label, Screen, StateCard } from "@/components/screen";
import { employeeRequest } from "@/lib/api";
import { useEmployee } from "@/providers/employee-provider";
import { useAppTheme } from "@/providers/theme-provider";

type AccessRequest = { id: string; requesterClerkId: string; requesterEmail: string; capability: EmployeeCapability; status: EmployeeAccessRequestStatus; reason: string | null; reviewerNote: string | null; createdAt: string };
export default function AccessRequestScreen() {
  const params = useLocalSearchParams<{ capability?: string; intendedDestination?: string }>(); const { getToken } = useAuth(); const employee = useEmployee(); const { colors } = useAppTheme(); const initial = employeeCapabilities.find((item) => item === params.capability) ?? "employee:access"; const [capability, setCapability] = useState<EmployeeCapability>(initial); const [reason, setReason] = useState(""); const [requests, setRequests] = useState<AccessRequest[]>([]); const [pendingReview, setPendingReview] = useState<AccessRequest[]>([]); const [notice, setNotice] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { const token = await getToken(); if (!token) throw new Error("Sign in to view access status."); const mine = employeeRequest<AccessRequest[]>("/api/v1/employee/access-requests", token); const review = employee.has("access:review") ? employeeRequest<AccessRequest[]>("/api/v1/employee/access-requests/review", token) : Promise.resolve([]); const [myRequests, reviewRequests] = await Promise.all([mine, review]); setRequests(myRequests); setPendingReview(reviewRequests); setNotice(null); } catch (error) { setNotice(error instanceof Error ? error.message : "Access status is unavailable."); } finally { setLoading(false); } }, [employee, getToken]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  async function submit() { try { const token = await getToken(); if (!token) throw new Error("Sign in to request access."); await employeeRequest("/api/v1/employee/access-requests", token, { method: "POST", body: JSON.stringify({ capability, sourceApp: "employee", intendedDestination: params.intendedDestination, reason }) }); setReason(""); setNotice("Your request was submitted for authorized review."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Request failed."); } }
  async function review(id: string, status: "approved" | "denied") { try { const token = await getToken(); if (!token) throw new Error("Session expired."); await employeeRequest(`/api/v1/employee/access-requests/review/${id}`, token, { method: "PATCH", body: JSON.stringify({ status }) }); setNotice(`Request ${status}.`); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Review failed."); } }
  const requestable = employeeCapabilities.filter((item) => !employee.data?.viewer.capabilities.includes(item));
  return <Screen eyebrow="NO SELF-APPROVAL" title="Access status" refresh={() => void load()} refreshing={loading}>{employee.data ? <StateCard title="Employee app enabled" body={`Signed in with ${employee.data.viewer.capabilities.length} active capabilities. Role and grants are rechecked while the app is open.`} /> : <StateCard title="Employee access required" body="This account is authenticated but cannot enter restricted areas. Submit a request; installing the app never grants access." />}{notice ? <StateCard title="Status" body={notice} /> : null}{pendingReview.length ? <><Label>Pending review</Label>{pendingReview.map((item) => <Card key={item.id}><Text style={{ color: colors.ink, fontWeight: "900" }}>{item.requesterEmail}</Text><Text style={{ color: colors.muted }}>{item.capability}</Text>{item.reason ? <Text style={{ color: colors.muted }}>{item.reason}</Text> : null}<View style={styles.actions}><Pressable onPress={() => void review(item.id, "approved")}><Text style={{ color: colors.brand, fontWeight: "900" }}>Approve</Text></Pressable><Pressable onPress={() => void review(item.id, "denied")}><Text style={{ color: colors.danger, fontWeight: "900" }}>Deny</Text></Pressable></View></Card>)}</> : null}{requestable.length ? <Card><Label>Request a capability</Label><View style={styles.chips}>{requestable.map((item) => <Pressable key={item} onPress={() => setCapability(item)} style={[styles.chip, { borderColor: colors.line, backgroundColor: capability === item ? colors.brandSoft : colors.surface }]}><Text style={{ color: colors.ink, fontWeight: "800", fontSize: 12 }}>{item}</Text></Pressable>)}</View><TextInput accessibilityLabel="Reason for access" value={reason} onChangeText={setReason} placeholder="Reason (optional)" multiline style={[styles.input, { borderColor: colors.line, color: colors.ink }]} /><Pressable onPress={() => void submit()} style={[styles.button, { backgroundColor: colors.brand }]}><Text style={{ color: colors.onBrand, fontWeight: "900" }}>Submit access request</Text></Pressable></Card> : null}{requests.length ? <><Label>Request history</Label>{requests.map((item) => <Card key={item.id}><View style={styles.row}><Text style={{ color: colors.ink, fontWeight: "900" }}>{item.capability}</Text><Text style={{ color: item.status === "approved" ? colors.brand : item.status === "denied" ? colors.danger : colors.accent, fontWeight: "900", textTransform: "uppercase", fontSize: 11 }}>{item.status}</Text></View><Text style={{ color: colors.muted, fontSize: 12 }}>{new Date(item.createdAt).toLocaleString()}</Text>{item.reviewerNote ? <Text style={{ color: colors.muted }}>Reviewer note: {item.reviewerNote}</Text> : null}</Card>)}</> : !loading ? <StateCard title="No access requests" body="Your request history will appear here." /> : null}</Screen>;
}
const styles = StyleSheet.create({ chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { borderWidth: 1, borderRadius: 20, paddingHorizontal: 11, paddingVertical: 8 }, input: { minHeight: 80, borderWidth: 1, borderRadius: 8, padding: 12, textAlignVertical: "top" }, button: { minHeight: 48, borderRadius: 8, alignItems: "center", justifyContent: "center" }, row: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, actions: { flexDirection: "row", gap: 18, marginTop: 4 } });
