import type { Story, WeatherSnapshot } from "@/lib/types";

const authors = {
  mara: {
    id: "author-mara-chen",
    name: "Mara Chen",
    role: "Senior local reporter",
    initials: "MC",
  },
  theo: {
    id: "author-theo-brooks",
    name: "Theo Brooks",
    role: "Weather editor",
    initials: "TB",
  },
  noah: {
    id: "author-noah-reed",
    name: "Noah Reed",
    role: "Investigative reporter",
    initials: "NR",
  },
  lena: {
    id: "author-lena-ortiz",
    name: "Lena Ortiz",
    role: "Sports producer",
    initials: "LO",
  },
  june: {
    id: "author-june-bell",
    name: "June Bell",
    role: "Community editor",
    initials: "JB",
  },
};

export const seedStories: Story[] = [
  {
    id: "story-harbor-plan",
    slug: "port-alder-council-unveils-harbor-resilience-plan",
    headline: "Port Alder unveils a $48M plan to protect the working waterfront",
    dek: "The proposal would raise two piers, restore tidal marsh and create a floodable public park along the east basin.",
    body: [
      "PORT ALDER — City leaders on Monday released the most detailed plan yet for protecting the working waterfront from rising seas and stronger winter storms.",
      "The $48 million proposal combines traditional infrastructure with restored shoreline. Two commercial piers would be raised, utilities would be moved above projected flood levels, and three acres of pavement would become a floodable park designed to hold stormwater.",
      "The plan follows nine months of meetings with fishermen, ferry operators, nearby residents and tribal environmental staff. A public hearing is scheduled for Thursday at City Hall, with a council vote expected next month.",
      "Funding would come from a mix of federal resilience grants, state transportation money and a local waterfront bond. Officials said construction could begin next spring if permits remain on schedule.",
    ],
    category: "local",
    categoryLabel: "Port Alder",
    location: "Port Alder",
    publishedAt: "2026-07-13T12:42:00-04:00",
    updatedAt: "2026-07-13T14:10:00-04:00",
    readingMinutes: 5,
    image:
      "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1800&q=86",
    imageAlt: "A coastal city and waterfront seen from above",
    author: authors.mara,
    tags: ["waterfront", "climate", "city hall"],
    status: "published",
    isBreaking: true,
    isDeveloping: true,
  },
  {
    id: "story-storm-watch",
    slug: "coastal-storm-watch-tuesday-high-tide",
    headline: "Coastal storm watch issued ahead of Tuesday’s high tide",
    dek: "Forecasters expect heavy rain, 40 mph gusts and minor flooding in the most vulnerable harbor streets.",
    body: [
      "A coastal storm watch is in effect for Harbor County through Tuesday evening as a slow-moving system approaches from the southwest.",
      "The Harborline weather team expects the most significant impacts between 7 a.m. and noon, when heavy rain overlaps with the morning high tide. Low-lying portions of Wharf Street and East Basin Road may briefly close.",
      "Residents are encouraged to secure outdoor furniture and avoid driving through standing water. No evacuation orders have been issued.",
    ],
    category: "weather",
    categoryLabel: "Weather",
    location: "Harbor County",
    publishedAt: "2026-07-13T11:18:00-04:00",
    readingMinutes: 3,
    image:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "Dark clouds gathering over a coastal landscape",
    author: authors.theo,
    tags: ["forecast", "storm", "flooding"],
    status: "published",
    isLive: true,
  },
  {
    id: "story-housing-audit",
    slug: "audit-finds-vacant-homes-missed-in-county-count",
    headline: "County audit finds hundreds of vacant homes missing from housing count",
    dek: "The discrepancy could change how state housing funds are distributed across five towns.",
    body: [
      "A new county audit identified 312 vacant residential properties that were not included in the region’s most recent housing inventory.",
      "The review began after Harborline Investigates compared utility shutoff records with municipal tax data. County officials then commissioned an independent parcel-by-parcel audit.",
      "Housing advocates say a more accurate count could help towns identify properties that can be rehabilitated and returned to year-round use.",
    ],
    category: "investigates",
    categoryLabel: "Harborline Investigates",
    location: "Harbor County",
    publishedAt: "2026-07-13T09:05:00-04:00",
    readingMinutes: 7,
    image:
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "A row of homes in a coastal community",
    author: authors.noah,
    tags: ["housing", "accountability", "data"],
    status: "published",
    isExclusive: true,
  },
  {
    id: "story-ferry-service",
    slug: "island-ferry-adds-late-summer-service",
    headline: "Island ferry adds late service for summer workers and visitors",
    dek: "The 10:30 p.m. departure will run Thursdays through Sundays until Labor Day.",
    body: [
      "Harbor County Ferry will add a late-night sailing between Port Alder and Northstar Island beginning this week.",
      "The seasonal trip is intended to serve hospitality workers whose shifts end after the current final ferry, as well as visitors attending evening events.",
    ],
    category: "local",
    categoryLabel: "Getting Around",
    location: "Northstar Island",
    publishedAt: "2026-07-13T08:30:00-04:00",
    readingMinutes: 2,
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "Blue water along a bright coastal shoreline",
    author: authors.june,
    tags: ["ferry", "transportation", "summer"],
    status: "published",
  },
  {
    id: "story-harbor-hawks",
    slug: "harbor-hawks-clinch-first-home-playoff-series",
    headline: "Harbor Hawks clinch their first home playoff series in six years",
    dek: "A sold-out crowd watched rookie Amari Wells score 28 in the regular-season finale.",
    body: [
      "The Harbor Hawks will open the regional playoffs at home after a 91-84 win Sunday night.",
      "Rookie guard Amari Wells led all scorers with 28 points, including a decisive three-pointer with 42 seconds remaining.",
    ],
    category: "sports",
    categoryLabel: "Local Sports",
    location: "Port Alder",
    publishedAt: "2026-07-12T22:16:00-04:00",
    readingMinutes: 4,
    image:
      "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "A basketball hoop inside a bright gymnasium",
    author: authors.lena,
    tags: ["basketball", "playoffs", "harbor hawks"],
    status: "published",
  },
  {
    id: "story-night-market",
    slug: "dockside-night-market-returns-friday",
    headline: "Dockside Night Market returns with 40 local makers and a new ferry shuttle",
    dek: "Here’s what to eat, hear and know before the waterfront festival opens Friday.",
    body: [
      "The Dockside Night Market returns to Pier Six on Friday with its largest lineup yet.",
      "Organizers say 40 makers, restaurants and community groups will take part. A free ferry shuttle will run every 20 minutes from the west parking lot.",
    ],
    category: "culture",
    categoryLabel: "Things to Do",
    location: "Port Alder",
    publishedAt: "2026-07-12T17:45:00-04:00",
    readingMinutes: 3,
    image:
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "A lively outdoor evening gathering with string lights",
    author: authors.june,
    tags: ["events", "food", "weekend"],
    status: "published",
  },
  {
    id: "story-school-meals",
    slug: "five-districts-expand-free-summer-meals",
    headline: "Five school districts expand free summer meal pickup",
    dek: "Families can now collect breakfast and lunch at 12 sites without registration.",
    body: [
      "Twelve schools and community centers across Harbor County are offering free breakfast and lunch pickup this summer.",
      "The expanded program is open to all children under 18, regardless of school enrollment or household income.",
    ],
    category: "local",
    categoryLabel: "Education",
    location: "Harbor County",
    publishedAt: "2026-07-12T13:20:00-04:00",
    readingMinutes: 2,
    image:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "A student working at a classroom desk",
    author: authors.mara,
    tags: ["schools", "families", "food access"],
    status: "published",
  },
];

export const weatherSeed: WeatherSnapshot = {
  location: "Port Alder",
  temperature: 72,
  feelsLike: 74,
  condition: "Clouds building",
  high: 76,
  low: 61,
  wind: "S 14 mph",
  humidity: 68,
  alert: "Coastal storm watch Tuesday, 6 a.m.–6 p.m.",
  hourly: [
    { time: "Now", temperature: 72, condition: "Cloudy" },
    { time: "4 PM", temperature: 74, condition: "Cloudy" },
    { time: "6 PM", temperature: 71, condition: "Showers" },
    { time: "8 PM", temperature: 68, condition: "Rain" },
    { time: "10 PM", temperature: 66, condition: "Rain" },
    { time: "12 AM", temperature: 64, condition: "Rain" },
  ],
};

export const studioDrafts = [
  {
    id: "draft-1",
    headline: "Library board considers extending weekend hours",
    section: "Local",
    owner: "Mara Chen",
    status: "review",
    updated: "8 min ago",
  },
  {
    id: "draft-2",
    headline: "Explainer: What the new harbor bond would fund",
    section: "Investigates",
    owner: "Noah Reed",
    status: "draft",
    updated: "24 min ago",
  },
  {
    id: "draft-3",
    headline: "Friday night market: road closures and ferry times",
    section: "Things to Do",
    owner: "June Bell",
    status: "scheduled",
    updated: "1 hr ago",
  },
];
