import { Activity, BarChart3, Clock3, FileText, Radio, TrendingUp, Users } from "lucide-react";
import { StudioGate } from "@/components/studio/studio-gate";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { studioDrafts } from "@/lib/seed";

export default function StudioDashboard() {
  return <StudioGate><div><div className="mb-7"><p className="text-sm font-medium text-primary">Monday, July 13</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Good afternoon, newsroom.</h1><p className="mt-1 text-sm text-muted-foreground">Here’s what’s moving across the Middlesex County desk.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard icon={<FileText />} label="Published today" value="14" detail="3 since noon" /><MetricCard icon={<Activity />} label="In review" value="6" detail="2 need an editor" /><MetricCard icon={<TrendingUp />} label="Readers now" value="2,418" detail="+18% vs. Monday" /><MetricCard icon={<Radio />} label="Live status" value="On air" detail="The New Jersey Courier Afternoon" /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle>Newsroom queue</CardTitle><CardDescription>Stories requiring action or scheduled today.</CardDescription></div><Badge variant="secondary">12 active</Badge></div></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Story</TableHead><TableHead>Owner</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Updated</TableHead></TableRow></TableHeader><TableBody>{studioDrafts.map((story) => <TableRow key={story.id}><TableCell><p className="max-w-sm font-medium">{story.headline}</p><p className="mt-0.5 text-xs text-muted-foreground">{story.section}</p></TableCell><TableCell><div className="flex items-center gap-2"><Avatar className="size-7"><AvatarFallback className="text-[0.6rem]">{story.owner.split(/\s+/).map((part) => part[0]).join("")}</AvatarFallback></Avatar><span className="text-xs">{story.owner}</span></div></TableCell><TableCell><Badge variant={story.status === "review" ? "default" : "secondary"} className="capitalize">{story.status}</Badge></TableCell><TableCell className="text-right text-xs text-muted-foreground">{story.updated}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card><div className="space-y-6"><Card><CardHeader><CardTitle>Today’s pace</CardTitle><CardDescription>14 of 18 planned stories published.</CardDescription></CardHeader><CardContent><Progress value={78} /><div className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><p className="text-2xl font-bold">78%</p><p className="text-xs text-muted-foreground">Plan complete</p></div><div><p className="text-2xl font-bold">4</p><p className="text-xs text-muted-foreground">Remaining</p></div></div></CardContent></Card><Card><CardHeader><CardTitle>Desk activity</CardTitle></CardHeader><CardContent className="space-y-5"><ActivityItem icon={<Users />} title="Mara sent a story to review" time="8 min ago" /><ActivityItem icon={<Clock3 />} title="Night Market scheduled for 5:00" time="31 min ago" /><ActivityItem icon={<BarChart3 />} title="Waterfront story crossed 10k reads" time="47 min ago" /></CardContent></Card></div></div></div></StudioGate>;
}

function MetricCard({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <Card><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><span className="rounded-md bg-primary/10 p-2 text-primary [&_svg]:size-4">{icon}</span></div></CardContent></Card>; }
function ActivityItem({ icon, title, time }: { icon: React.ReactNode; title: string; time: string }) { return <div className="flex gap-3"><span className="mt-0.5 text-muted-foreground [&_svg]:size-4">{icon}</span><div><p className="text-sm font-medium leading-5">{title}</p><p className="mt-0.5 text-xs text-muted-foreground">{time}</p></div></div>; }
