import { sha256Hex } from "./sha256";
import type { FeatureManifest } from "./feature-manifest";
import type { FeatureModule } from "./feature-host";

const checksum = (id: string) => sha256Hex(`platform-reference:${id}`);
const base = (id: string, displayName: string, entitlement: string): FeatureManifest => ({ schemaVersion: 1, id, displayName, description: `${displayName} reference feature`, version: "0.1.0", publisher: "platform.reference", minimumHostRuntime: "0.1.0", maximumTestedHostRuntime: "0.1.0", supportedPlatforms: ["web", "ios", "android", "tvos", "androidtv", "node"], entryPoint: `features/${id}`, lifecyclePolicy: { start: "lazy", background: "suspend", failure: "isolate" }, killSwitchKey: id, requiredHostCapabilities: ["logging"], optionalHostCapabilities: [], licenseEntitlement: entitlement, dependencies: [], conflicts: [], configurationSchema: {}, commands: [], eventsEmitted: [], eventsConsumed: [], uiSurfaces: [], backgroundServices: [], permissions: [], dataMigrations: [], featureFlags: [], privacy: { dataCategories: [], purposes: [], retentionDays: 0, sharesExternally: false }, resourceRequirements: { maxMemoryMb: 32, maxStorageMb: 8, networkRequired: false }, packageChecksum: checksum(id) });
export const diagnosticsFeatureManifest = base("platform.diagnostics", "Diagnostics utility", "feature.diagnostics");
export const uiFeatureManifest: FeatureManifest = { ...base("platform.status-card", "Status card UI", "feature.status-card"), requiredHostCapabilities: ["logging", "ui-overlays", "theme"], uiSurfaces: [{ id: "status-card", kind: "component" }], dependencies: [{ id: diagnosticsFeatureManifest.id, range: "^0.1.0", optional: false }] };
export const animationFeatureManifest: FeatureManifest = { ...base("platform.animation", "Animation runtime", "feature.animation"), requiredHostCapabilities: ["logging", "animation", "accessibility", "app-lifecycle"], optionalHostCapabilities: ["theme", "haptics"], commands: [{ id: "play", inputSchema: { type: "object" }, outputSchema: {} }], eventsEmitted: [{ id: "animation-event", payloadSchema: { type: "object" } }], dependencies: [{ id: diagnosticsFeatureManifest.id, range: "^0.1.0", optional: false }] };

export class DiagnosticsFeature implements FeatureModule { start(context: Parameters<NonNullable<FeatureModule["start"]>>[0]) { const logger = context.services.logging as { log(message: string): void }; logger.log(`Started ${context.manifest.id}@${context.manifest.version}`); } }
export class StatusCardFeature implements FeatureModule { register(context: Parameters<NonNullable<FeatureModule["register"]>>[0]) { context.emitDiagnostic("UI_REGISTERED", "Status card surface registered through host UI services."); } }
export class AnimationFeature implements FeatureModule { initialize(context: Parameters<NonNullable<FeatureModule["initialize"]>>[0]) { context.emitDiagnostic("ANIMATION_READY", "Animation compiler/runtime capability initialized."); } }
