"use client";

import { useState } from "react";
import { CheckCircle2, LoaderCircle, Send } from "lucide-react";

type Question = { id: string; prompt: string; questionType: "rating" | "multiple_choice" | "yes_no" | "free_response"; required: boolean; options: string[] };

export function PreviewFeedback({ slug, questions, initial }: { slug: string; questions: Question[]; initial?: { overallRating: number | null; writtenFeedback: string; answers: Array<{ questionId: string; value: string | number | boolean }> } | null }) {
  const [rating, setRating] = useState<number | null>(initial?.overallRating ?? null);
  const [written, setWritten] = useState(initial?.writtenFeedback ?? "");
  const [answers, setAnswers] = useState<Record<string, string | number | boolean>>(() => Object.fromEntries(initial?.answers.map((answer) => [answer.questionId, answer.value]) ?? []));
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch(`/api/v1/plus/previews/${encodeURIComponent(slug)}/feedback`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ overallRating: rating, writtenFeedback: written, answers: Object.entries(answers).map(([questionId, value]) => ({ questionId, value })) }) }); const payload = await response.json() as { error?: { message?: string } }; setMessage(response.ok ? "Your private feedback was submitted. Thank you." : payload.error?.message || "Feedback could not be submitted."); setBusy(false); }
  return <form className="plus-preview-feedback" onSubmit={(event) => void submit(event)}><p>The Courier Cut feedback</p><h2>Help shape the final release.</h2><label><span>Overall reaction</span><div className="plus-rating" role="radiogroup" aria-label="Overall reaction">{[1,2,3,4,5].map((value) => <button type="button" key={value} className={rating === value ? "is-active" : ""} onClick={() => setRating(value)} aria-pressed={rating === value}>{value}</button>)}</div></label><label><span>Written feedback</span><textarea rows={6} value={written} onChange={(event) => setWritten(event.target.value)} placeholder="What worked, what did not, and what should the team know?" /></label>{questions.map((question) => <QuestionField key={question.id} question={question} value={answers[question.id]} set={(value) => setAnswers((current) => ({ ...current, [question.id]: value }))} />)}<button type="submit" disabled={busy}>{busy ? <LoaderCircle className="animate-spin" /> : initial ? <CheckCircle2 /> : <Send />} {initial ? "Update feedback" : "Submit feedback"}</button>{message ? <span role="status">{message}</span> : null}</form>;
}
function QuestionField({ question, value, set }: { question: Question; value: string | number | boolean | undefined; set: (value: string | number | boolean) => void }) { return <label><span>{question.prompt}{question.required ? " *" : ""}</span>{question.questionType === "free_response" ? <textarea required={question.required} rows={4} value={String(value ?? "")} onChange={(event) => set(event.target.value)} /> : question.questionType === "rating" ? <select required={question.required} value={String(value ?? "")} onChange={(event) => set(Number(event.target.value))}><option value="">Choose a rating</option>{[1,2,3,4,5].map((item) => <option key={item} value={item}>{item} / 5</option>)}</select> : question.questionType === "yes_no" ? <select required={question.required} value={typeof value === "boolean" ? String(value) : ""} onChange={(event) => set(event.target.value === "true")}><option value="">Choose an answer</option><option value="true">Yes</option><option value="false">No</option></select> : <select required={question.required} value={String(value ?? "")} onChange={(event) => set(event.target.value)}><option value="">Choose an answer</option>{question.options.map((option) => <option key={option} value={option}>{option}</option>)}</select>}</label>; }
