import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { AnimationRuntime, compileAnimation, springProgress } from "../src/animation/index";
const bytes = compileAnimation(readFileSync(new URL("../examples/animation-showcase/welcome.pani", import.meta.url), "utf8")).packageBytes;
test("timeline evaluation, binding, state transition and event order are deterministic", () => { const runtime = new AnimationRuntime(bytes, { scene: "Welcome" }); const events: string[] = []; runtime.onEvent((event) => events.push(event)); runtime.setInput("userName", "Taylor"); assert.equal(runtime.send("WelcomeFlow", "ready", 100), true); const start = runtime.tick(100); const end = runtime.tick(720); assert.equal(start.activeStateMachines.WelcomeFlow, "ready"); assert.equal(end.nodes.find((node) => node.id === "title")?.properties.text, "Welcome, Taylor"); assert.deepEqual(events, ["welcomeReady"]); assert.equal(runtime.send("WelcomeFlow", "continue", 800), true); runtime.tick(1320); assert.deepEqual(events, ["welcomeReady", "continueRequested"]); });
test("reduced motion substitutes the declared timeline", () => { const runtime = new AnimationRuntime(bytes, { scene: "Welcome", reducedMotion: true }); runtime.send("WelcomeFlow", "ready", 0); const frame = runtime.tick(180); assert.equal(frame.timeMs, 180); assert.equal(frame.nodes.find((node) => node.id === "title")?.properties.opacity, 1); assert.equal(frame.nodes.find((node) => node.id === "mark")?.properties.opacity, 0); });
test("spring solver is stable at boundaries", () => { assert.equal(springProgress(0, 620), 0); assert.equal(springProgress(620, 620), 1); assert.ok(Number.isFinite(springProgress(310, 620))); });
test("interruption can retarget without jumping to the next timeline origin", () => { const runtime = new AnimationRuntime(bytes, { scene: "Welcome" }); runtime.play("entrance", 0); const before = runtime.tick(300).nodes.find((node) => node.id === "title")?.properties.opacity; runtime.play("exit", 300, "smoothlyRetarget"); const after = runtime.tick(300).nodes.find((node) => node.id === "title")?.properties.opacity; assert.equal(after, before); });
