import assert from "node:assert/strict";
import test from "node:test";
import { DiagnosticsFeature, FeatureHost, diagnosticsFeatureManifest } from "../src/index";

const verifier = { async verify() { return true; } };
test("required capabilities are denied before module registration", async () => { const host = new FeatureHost({ runtimeVersion: "0.1.0", platform: "node", permittedCapabilities: new Set() }, {}, { async hasEntitlement() { return true; } }, verifier); host.discover(diagnosticsFeatureManifest, new DiagnosticsFeature()); await assert.rejects(() => host.startAll(), /missing required capabilities/); });
test("missing entitlement stops lifecycle before registration", async () => { let registered = false; const host = new FeatureHost({ runtimeVersion: "0.1.0", platform: "node", permittedCapabilities: new Set(["logging"]) }, { logging: { log() {} } }, { async hasEntitlement() { return false; } }, verifier); host.discover(diagnosticsFeatureManifest, { register() { registered = true; } }); await assert.rejects(() => host.startAll(), /Missing entitlement/); assert.equal(registered, false); });
test("circular dependencies are diagnosed", async () => { const one = { ...diagnosticsFeatureManifest, id: "test.one", dependencies: [{ id: "test.two", range: "^0.1.0", optional: false }] }; const two = { ...diagnosticsFeatureManifest, id: "test.two", dependencies: [{ id: "test.one", range: "^0.1.0", optional: false }] }; const host = new FeatureHost({ runtimeVersion: "0.1.0", platform: "node", permittedCapabilities: new Set(["logging"]) }, { logging: {} }, { async hasEntitlement() { return true; } }, verifier); host.discover(one, {}); host.discover(two, {}); await host.verifyAll(); assert.throws(() => host.resolveOrder(), /Circular/); });
test("upgrade and rollback hooks are explicit and auditable", async () => { const calls: string[] = []; const host = new FeatureHost({ runtimeVersion: "0.1.0", platform: "node", permittedCapabilities: new Set(["logging"]) }, { logging: {} }, { async hasEntitlement() { return true; } }, verifier); host.discover(diagnosticsFeatureManifest, { upgrade(from) { calls.push(`up:${from}`); }, rollback(to) { calls.push(`down:${to}`); } }); await host.startAll(); await host.upgradeFeature(diagnosticsFeatureManifest.id, "0.0.9"); await host.rollbackFeature(diagnosticsFeatureManifest.id, "0.0.9"); assert.deepEqual(calls, ["up:0.0.9", "down:0.0.9"]); assert.ok(host.diagnostics.some((item) => item.code === "FEATURE_UPGRADED")); });
