import assert from "node:assert/strict";
import test from "node:test";
import { verifySignedReceipt } from "../src/licensing/index";
import { createDevelopmentLicenseFixture, firstPartyWebIdentity, thirdPartyIdentity } from "../examples/development-license-fixture";

process.env.PLATFORM_DEV_LICENSE_MODE = "true";
test("first-party entitlement is an ordinary signed receipt bound to exact identity", async () => { const { service, firstParty } = createDevelopmentLicenseFixture(); const receipt = await service.issueFirstPartyReceipt(firstParty.id, firstPartyWebIdentity, "install-a"); const valid = await service.validateEntitlement(receipt, { application: firstPartyWebIdentity, productId: "platform-runtime" }); assert.equal(valid.ok, true); const wrong = await service.validateEntitlement(receipt, { application: { ...firstPartyWebIdentity, host: "other.example" }, productId: "platform-runtime" }); assert.deepEqual(wrong.ok ? null : wrong.code, "wrong_application"); });
test("ordinary third party requires a license and rejects another app", async () => { const { service, thirdParty } = createDevelopmentLicenseFixture(); await assert.rejects(() => service.activate({ licenseKey: "not-a-license", applicationIdentity: thirdPartyIdentity, pseudonymousDeviceId: "x", idempotencyKey: "bad" }), /invalid/); const active = await service.activate({ licenseKey: thirdParty.licenseKey, applicationIdentity: thirdPartyIdentity, pseudonymousDeviceId: "x", idempotencyKey: "good" }); const wrongIdentity = { ...thirdPartyIdentity, applicationId: "copied-app" }; const validation = await service.validateEntitlement(active.receipt, { application: wrongIdentity, productId: "platform-runtime" }); assert.deepEqual(validation.ok ? null : validation.code, "wrong_application"); });
test("tampering, revocation and key rotation behave deterministically", async () => { const { service, thirdParty } = createDevelopmentLicenseFixture(); const active = await service.activate({ licenseKey: thirdParty.licenseKey, applicationIdentity: thirdPartyIdentity, pseudonymousDeviceId: "x", idempotencyKey: "good" }); const keysBefore = await service.publicVerificationKeys(); await service.rotateSigningKey("admin"); const stillValid = verifySignedReceipt(active.receipt, await service.publicVerificationKeys(), { issuer: "https://licenses.platform.local", audience: "platform-runtime", productId: "platform-runtime", application: thirdPartyIdentity }); assert.equal(stillValid.ok, true); assert.ok((await service.publicVerificationKeys()).length > keysBefore.length); const tampered = { ...active.receipt, payload: `${active.receipt.payload.slice(0, -1)}A` }; assert.deepEqual(verifySignedReceipt(tampered, await service.publicVerificationKeys(), { issuer: "https://licenses.platform.local", audience: "platform-runtime", productId: "platform-runtime", application: thirdPartyIdentity }).ok, false); service.revokeLicense(thirdParty.license.id, "admin"); const revoked = await service.validateEntitlement(active.receipt, { application: thirdPartyIdentity, productId: "platform-runtime" }); assert.deepEqual(revoked.ok ? null : revoked.code, "revoked"); });
test("activation mutations are idempotent", async () => { const { service, thirdParty } = createDevelopmentLicenseFixture(); const input = { licenseKey: thirdParty.licenseKey, applicationIdentity: thirdPartyIdentity, pseudonymousDeviceId: "x", idempotencyKey: "same" }; const first = await service.activate(input); const second = await service.activate(input); assert.equal(second.installationId, first.installationId); assert.equal(service.activations.length, 1); });
test("offline leases are signed, bounded, recorded, and disabled installations cannot refresh", async () => { const { service, thirdParty } = createDevelopmentLicenseFixture(); const active = await service.activate({ licenseKey: thirdParty.licenseKey, applicationIdentity: thirdPartyIdentity, pseudonymousDeviceId: "offline-x", idempotencyKey: "offline" }); const lease = await service.issueOfflineLease(active.installationId); const validation = await service.validateEntitlement(lease.receipt, { application: thirdPartyIdentity, productId: "platform-runtime" }); assert.equal(validation.ok, true); assert.equal(validation.ok && validation.claims.offline, true); assert.equal(service.offlineLeases.length, 1); assert.equal(service.deactivateInstallation(active.installationId), true); await assert.rejects(() => service.refreshOnlineLease(active.installationId), /not active/); });
test("development fixture cannot run in production", () => { const previous = process.env.NODE_ENV; process.env.NODE_ENV = "production"; assert.throws(() => createDevelopmentLicenseFixture(), /disabled/); process.env.NODE_ENV = previous; });
