import type { FeatureIR } from "@visual-feature/model";

export function ComposerData({ feature, onMockName }: { feature: FeatureIR; onMockName: (value: string) => void }) {
  return <div className="composer-data">
    <aside className="data-models"><div className="composer-panel-title"><span>DATA MODELS</span><small>{feature.dataModels.length} records</small></div>{feature.dataModels.map((model) => <section key={model.id}><header><i>D</i><div><strong>{model.name}</strong><small>{model.id}</small></div></header><table><thead><tr><th>Field</th><th>Type</th><th>Rules</th></tr></thead><tbody>{model.fields.map((field) => <tr key={field.id}><td>{field.name}</td><td><code>{field.type}{field.optional ? "?" : ""}</code></td><td>{field.validation?.required ? "required" : "—"}</td></tr>)}</tbody></table></section>)}</aside>
    <section className="binding-map"><div className="graph-head"><span>REACTIVE BINDINGS</span><small>Cycle checked</small></div><div className="binding-columns"><article><h3>Application data</h3>{feature.state.map((field) => <div className="data-node" key={field.id}><span>{field.scope}</span><strong>{field.name}</strong><code>{field.type}</code></div>)}</article><div className="binding-lines" aria-hidden="true"><i /><i /><i /></div><article><h3>Visual properties</h3>{feature.screens.flatMap((screen) => screen.root.children).flatMap((component) => component.bindings).map((binding) => <div className="data-node target" key={binding.id}><span>{binding.changeAnimation ?? "immediate"}</span><strong>{binding.targetComponentId.split(".").at(-1)}.{binding.targetProperty}</strong><code>← {binding.expression}</code></div>)}</article></div></section>
    <aside className="mock-data"><div className="composer-panel-title"><span>MOCK DATA</span><small>Development fixture</small></div><label><span>SelectedProduct.name</span><input value={String((feature.state.find((item) => item.name === "SelectedProduct")?.initialValue as Record<string, unknown> | undefined)?.name ?? "")} onChange={(event) => onMockName(event.target.value)} /></label><label><span>SelectedProduct.price</span><input value={String((feature.state.find((item) => item.name === "SelectedProduct")?.initialValue as Record<string, unknown> | undefined)?.price ?? "")} readOnly /></label><h3>Connector contracts</h3>{feature.connectors.map((connector) => <div className="connector-card" key={connector.id}><span>{connector.kind}</span><strong>{connector.name}</strong><small>{connector.credentialReference ?? "No credential"}</small>{connector.operations.map((operation) => <code key={operation.id}>{operation.method} {operation.path} → {operation.outputType}</code>)}</div>)}</aside>
  </div>;
}
