import { behaviorSuggestions, componentDefinition, type BehaviorFlow, type FeatureComponent } from "@visual-feature/model";

export function ComposerBehavior({ selected, flow, source, onAddAction }: { selected?: FeatureComponent; flow?: BehaviorFlow; source: string; onAddAction: (action: string) => void }) {
  const definition = selected ? componentDefinition(selected.type) : undefined;
  const suggestions = selected ? behaviorSuggestions(selected.type) : [];
  return <div className="composer-behavior">
    <aside className="guided-builder"><div className="composer-panel-title"><span>ADD BEHAVIOR</span><small>Guided</small></div>{selected && definition ? <><header><i>{selected.type.slice(0, 1).toUpperCase()}</i><div><strong>{selected.name}</strong><small>{definition.label}</small></div></header><label><span>When</span><select aria-label="Behavior trigger" defaultValue={flow?.trigger.event ?? definition.events[0]}>{definition.events.map((event) => <option key={event}>{event}</option>)}</select></label><h3>Relevant actions</h3><div className="suggestion-grid">{suggestions.map((action) => <button type="button" key={action} onClick={() => onAddAction(action)}><span>＋</span>{action}</button>)}</div><p className="schema-note">Suggestions come from the component schema: supported events, actions, capabilities and platform compatibility.</p></> : <p className="composer-empty">Select a component in Design mode before attaching behavior.</p>}</aside>
    <section className="behavior-graph" aria-label="Typed behavior graph"><div className="graph-head"><span>BEHAVIOR GRAPH</span><small>{flow ? `${flow.nodes.length} nodes · ${flow.edges.length} typed connections` : "No attached flow"}</small><button type="button">Fit graph</button></div>{flow ? <div className="graph-scroll"><svg aria-hidden="true" viewBox="0 0 780 1020" preserveAspectRatio="none">{flow.edges.map((edge) => { const from = flow.nodes.find((node) => node.id === edge.fromNodeId); const to = flow.nodes.find((node) => node.id === edge.toNodeId); if (!from || !to) return null; return <path key={edge.id} d={`M ${from.position.x + 210} ${from.position.y + 48} C ${from.position.x + 250} ${from.position.y + 80}, ${to.position.x + 160} ${to.position.y - 28}, ${to.position.x + 200} ${to.position.y}`} data-outcome={edge.outcome ?? "next"} />; })}</svg>{flow.nodes.map((node) => <button type="button" className={`graph-node ${node.kind}`} style={{ left: node.position.x + 230, top: node.position.y }} key={node.id}><span>{node.kind.replace("-", " ")}</span><strong>{node.label}</strong><small>{node.inputs.map((port) => port.valueType).join(", ") || "trigger"} → {node.outputs.map((port) => port.label).join(" · ") || "end"}</small></button>)}</div> : <div className="composer-empty">Choose an event and action to create a typed flow.</div>}</section>
    <aside className="english-preview"><div className="composer-panel-title"><span>CONTROLLED ENGLISH</span><small>Synchronized</small></div><pre>{source}</pre><footer><i /> Deterministic grammar · no AI interpreter</footer></aside>
  </div>;
}
