import type { FeatureIR, MotionKeyframe } from "@visual-feature/model";

export function ComposerMotion({ feature, selectedMotionId, onSelectMotion, onKeyframe }: { feature: FeatureIR; selectedMotionId: string; onSelectMotion: (id: string) => void; onKeyframe: (trackId: string, keyframeId: string, patch: Partial<MotionKeyframe>) => void }) {
  const motion = feature.motions.find((item) => item.id === selectedMotionId) ?? feature.motions[0];
  const firstTrack = motion?.tracks[0]; const maximum = Math.max(1, ...firstTrack?.keyframes.map((item) => item.value) ?? [1]);
  const points = firstTrack?.keyframes.map((item) => `${24 + item.timeMs / Math.max(1, motion?.durationMs ?? 1) * 472},${190 - item.value / maximum * 140}`).join(" ") ?? "";
  return <div className="composer-motion">
    <aside className="motion-layers"><div className="composer-panel-title"><span>COMPOSITIONS</span><small>{feature.motions.length}</small></div>{feature.motions.map((item) => <button type="button" className={item.id === motion?.id ? "active" : ""} key={item.id} onClick={() => onSelectMotion(item.id)}><i>◇</i><span>{item.name}<small>{item.durationMs}ms · {item.tracks.length} tracks</small></span></button>)}<h3>Motion architecture</h3><p>Property tracks, named markers, reduced-motion alternatives, cubic curves, springs and runtime data bindings share the canonical Feature IR.</p></aside>
    <section className="curve-editor"><div className="graph-head"><span>VALUE GRAPH</span><small>{firstTrack ? `${firstTrack.targetComponentId.split(".").at(-1)}.${firstTrack.property}` : "No track"}</small><button type="button">Fit selection</button></div><svg viewBox="0 0 520 220" role="img" aria-label="Editable keyframe value curve"><defs><pattern id="curve-grid" width="52" height="44" patternUnits="userSpaceOnUse"><path d="M 52 0 L 0 0 0 44" fill="none" stroke="currentColor" strokeOpacity=".13" /></pattern></defs><rect width="520" height="220" fill="url(#curve-grid)" /><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2" />{firstTrack?.keyframes.map((keyframe) => <circle key={keyframe.id} cx={24 + keyframe.timeMs / Math.max(1, motion?.durationMs ?? 1) * 472} cy={190 - keyframe.value / maximum * 140} r="5" />)}</svg><div className="curve-legend"><span><i /> Value</span><span>Bezier handles and velocity fields are stored per keyframe</span></div></section>
    <aside className="keyframe-inspector"><div className="composer-panel-title"><span>KEYFRAMES</span><small>Numerical editing</small></div>{firstTrack?.keyframes.map((keyframe) => <fieldset key={keyframe.id}><legend>{keyframe.label ?? keyframe.id.split(".").at(-1)}</legend><label><span>Time</span><input type="number" value={keyframe.timeMs} onChange={(event) => onKeyframe(firstTrack.id, keyframe.id, { timeMs: Number(event.target.value) })} /><b>ms</b></label><label><span>Value</span><input type="number" step="0.01" value={keyframe.value} onChange={(event) => onKeyframe(firstTrack.id, keyframe.id, { value: Number(event.target.value) })} /></label><label><span>Interpolation</span><select value={keyframe.interpolation} onChange={(event) => onKeyframe(firstTrack.id, keyframe.id, { interpolation: event.target.value as MotionKeyframe["interpolation"] })}><option>linear</option><option>hold</option><option>step</option><option>bezier</option><option>spring</option></select></label>{keyframe.cubicBezier && <code>cubic {keyframe.cubicBezier.join(" · ")}</code>}</fieldset>)}</aside>
  </div>;
}
