import { sha256 } from "../core/sha256";
import { Builder, ByteBuffer, type Offset } from "flatbuffers";
import { canonicalJson } from "../licensing/canonical";
import type { CompiledAnimation, ComponentNode, InputNode, KeyframeNode, MachineNode, ScalarValue, SceneNode, SourceSpan, TimelineNode, TrackNode, TransitionNode } from "./types";

const magic = new Uint8Array([0x50, 0x4c, 0x41, 0x54, 0x41, 0x4e, 0x49, 0x00]);
const headerSize = 48; const containerVersion = 1; const fileIdentifier = "PANI";
const vector = (builder: Builder, offsets: Offset[]) => { builder.startVector(4, offsets.length, 4); for (let index = offsets.length - 1; index >= 0; index -= 1) builder.addOffset(offsets[index]!); return builder.endVector(); };
const table = (builder: Builder, fields: number, add: () => void) => { builder.startObject(fields); add(); return builder.endObject(); };
const strings = (builder: Builder, values: string[]) => vector(builder, values.map((value) => builder.createString(value)));

function keyframeOffset(builder: Builder, keyframe: KeyframeNode) { const easing = builder.createString(keyframe.easing); return table(builder, 3, () => { builder.addFieldInt32(0, keyframe.timeMs, 0); builder.addFieldFloat64(1, keyframe.value, 0); builder.addFieldOffset(2, easing, 0); }); }
function trackOffset(builder: Builder, track: TrackNode) { const target = builder.createString(track.target); const keyframes = vector(builder, track.keyframes.map((item) => keyframeOffset(builder, item))); return table(builder, 2, () => { builder.addFieldOffset(0, target, 0); builder.addFieldOffset(1, keyframes, 0); }); }
function timelineOffset(builder: Builder, timeline: TimelineNode) { const name = builder.createString(timeline.name); const tracks = vector(builder, timeline.tracks.map((item) => trackOffset(builder, item))); return table(builder, 3, () => { builder.addFieldOffset(0, name, 0); builder.addFieldInt32(1, timeline.durationMs, 0); builder.addFieldOffset(2, tracks, 0); }); }
function componentOffset(builder: Builder, component: ComponentNode) { const id = builder.createString(component.id); const kind = builder.createString(component.kind); const properties = builder.createString(canonicalJson(component.properties)); return table(builder, 3, () => { builder.addFieldOffset(0, id, 0); builder.addFieldOffset(1, kind, 0); builder.addFieldOffset(2, properties, 0); }); }
function inputOffset(builder: Builder, input: InputNode) { const name = builder.createString(input.name); const type = builder.createString(input.type); const value = builder.createString(canonicalJson(input.defaultValue)); return table(builder, 3, () => { builder.addFieldOffset(0, name, 0); builder.addFieldOffset(1, type, 0); builder.addFieldOffset(2, value, 0); }); }
function transitionOffset(builder: Builder, transition: TransitionNode) { const from = builder.createString(transition.from); const to = builder.createString(transition.to); const event = builder.createString(transition.event); const timeline = builder.createString(transition.timeline ?? ""); const emitted = builder.createString(transition.emittedEvent ?? ""); return table(builder, 5, () => { builder.addFieldOffset(0, from, 0); builder.addFieldOffset(1, to, 0); builder.addFieldOffset(2, event, 0); builder.addFieldOffset(3, timeline, 0); builder.addFieldOffset(4, emitted, 0); }); }
function machineOffset(builder: Builder, machine: MachineNode) { const name = builder.createString(machine.name); const initial = builder.createString(machine.initialState); const states = strings(builder, machine.states); const transitions = vector(builder, machine.transitions.map((item) => transitionOffset(builder, item))); return table(builder, 4, () => { builder.addFieldOffset(0, name, 0); builder.addFieldOffset(1, initial, 0); builder.addFieldOffset(2, states, 0); builder.addFieldOffset(3, transitions, 0); }); }
function sceneOffset(builder: Builder, scene: SceneNode) { const name = builder.createString(scene.name); const inputs = vector(builder, scene.inputs.map((item) => inputOffset(builder, item))); const components = vector(builder, scene.components.map((item) => componentOffset(builder, item))); const timelines = vector(builder, scene.timelines.map((item) => timelineOffset(builder, item))); const machines = vector(builder, scene.machines.map((item) => machineOffset(builder, item))); const reduced = builder.createString(scene.reducedMotionTimeline ?? ""); return table(builder, 6, () => { builder.addFieldOffset(0, name, 0); builder.addFieldOffset(1, inputs, 0); builder.addFieldOffset(2, components, 0); builder.addFieldOffset(3, timelines, 0); builder.addFieldOffset(4, machines, 0); builder.addFieldOffset(5, reduced, 0); }); }

export function encodeAnimationFlatbuffer(compiled: CompiledAnimation) {
  const builder = new Builder(4096); const minimum = builder.createString(compiled.minimumRuntime); const compiler = builder.createString(compiled.compilerVersion); const sourceHash = builder.createString(compiled.sourceHash); const scenes = vector(builder, compiled.scenes.map((item) => sceneOffset(builder, item))); const features = strings(builder, compiled.requiredFeatures); const root = table(builder, 6, () => { builder.addFieldInt32(0, compiled.schemaVersion, 0); builder.addFieldOffset(1, minimum, 0); builder.addFieldOffset(2, compiler, 0); builder.addFieldOffset(3, sourceHash, 0); builder.addFieldOffset(4, scenes, 0); builder.addFieldOffset(5, features, 0); }); builder.finish(root, fileIdentifier); return builder.asUint8Array();
}
const span: SourceSpan = { start: { offset: 0, line: 0, column: 0 }, end: { offset: 0, line: 0, column: 0 } };
function stringField(bb: ByteBuffer, pos: number, slot: number) { const offset = bb.__offset(pos, 4 + slot * 2); return offset ? String(bb.__string(pos + offset)) : ""; }
function intField(bb: ByteBuffer, pos: number, slot: number) { const offset = bb.__offset(pos, 4 + slot * 2); return offset ? bb.readInt32(pos + offset) : 0; }
function doubleField(bb: ByteBuffer, pos: number, slot: number) { const offset = bb.__offset(pos, 4 + slot * 2); return offset ? bb.readFloat64(pos + offset) : 0; }
function tableVector(bb: ByteBuffer, pos: number, slot: number) { const offset = bb.__offset(pos, 4 + slot * 2); if (!offset) return [] as number[]; const start = bb.__vector(pos + offset); return Array.from({ length: bb.__vector_len(pos + offset) }, (_, index) => bb.__indirect(start + index * 4)); }
function stringVector(bb: ByteBuffer, pos: number, slot: number) { const offset = bb.__offset(pos, 4 + slot * 2); if (!offset) return []; const start = bb.__vector(pos + offset); return Array.from({ length: bb.__vector_len(pos + offset) }, (_, index) => String(bb.__string(start + index * 4))); }
function readKeyframe(bb: ByteBuffer, pos: number): KeyframeNode { return { timeMs: intField(bb, pos, 0), value: doubleField(bb, pos, 1), easing: stringField(bb, pos, 2), span }; }
function readTrack(bb: ByteBuffer, pos: number): TrackNode { return { target: stringField(bb, pos, 0), keyframes: tableVector(bb, pos, 1).map((item) => readKeyframe(bb, item)), span }; }
function readTimeline(bb: ByteBuffer, pos: number): TimelineNode { return { name: stringField(bb, pos, 0), durationMs: intField(bb, pos, 1), tracks: tableVector(bb, pos, 2).map((item) => readTrack(bb, item)), span }; }
function readInput(bb: ByteBuffer, pos: number): InputNode { return { name: stringField(bb, pos, 0), type: stringField(bb, pos, 1) as InputNode["type"], defaultValue: JSON.parse(stringField(bb, pos, 2)) as ScalarValue, span }; }
function readComponent(bb: ByteBuffer, pos: number): ComponentNode { return { id: stringField(bb, pos, 0), kind: stringField(bb, pos, 1) as ComponentNode["kind"], properties: JSON.parse(stringField(bb, pos, 2)) as Record<string, ScalarValue>, span }; }
function readTransition(bb: ByteBuffer, pos: number): TransitionNode { const timeline = stringField(bb, pos, 3); const emittedEvent = stringField(bb, pos, 4); return { from: stringField(bb, pos, 0), to: stringField(bb, pos, 1), event: stringField(bb, pos, 2), ...(timeline ? { timeline } : {}), ...(emittedEvent ? { emittedEvent } : {}), span }; }
function readMachine(bb: ByteBuffer, pos: number): MachineNode { return { name: stringField(bb, pos, 0), initialState: stringField(bb, pos, 1), states: stringVector(bb, pos, 2), transitions: tableVector(bb, pos, 3).map((item) => readTransition(bb, item)), span }; }
function readScene(bb: ByteBuffer, pos: number): SceneNode { const reducedMotionTimeline = stringField(bb, pos, 5); return { name: stringField(bb, pos, 0), inputs: tableVector(bb, pos, 1).map((item) => readInput(bb, item)), components: tableVector(bb, pos, 2).map((item) => readComponent(bb, item)), timelines: tableVector(bb, pos, 3).map((item) => readTimeline(bb, item)), machines: tableVector(bb, pos, 4).map((item) => readMachine(bb, item)), ...(reducedMotionTimeline ? { reducedMotionTimeline } : {}), span }; }

export function decodeAnimationFlatbuffer(payload: Uint8Array): CompiledAnimation {
  const bb = new ByteBuffer(payload); if (!bb.__has_identifier(fileIdentifier)) throw new Error("FlatBuffers file identifier is invalid"); const root = bb.position() + bb.readInt32(bb.position()); const schemaVersion = intField(bb, root, 0); if (schemaVersion !== 1) throw new Error(`Unsupported animation schema ${schemaVersion}`); return { schemaVersion: 1, minimumRuntime: stringField(bb, root, 1), compilerVersion: stringField(bb, root, 2), sourceHash: stringField(bb, root, 3), scenes: tableVector(bb, root, 4).map((item) => readScene(bb, item)), requiredFeatures: stringVector(bb, root, 5) };
}

export function wrapAnimationPackage(payload: Uint8Array) { const output = new Uint8Array(headerSize + payload.length); output.set(magic); const view = new DataView(output.buffer); view.setUint16(8, containerVersion, true); view.setUint16(10, 0, true); view.setUint32(12, payload.length, true); output.set(sha256(payload), 16); output.set(payload, headerSize); return output; }
export function verifyAndUnwrapAnimationPackage(input: Uint8Array, limits = { maxPackageBytes: 16 * 1024 * 1024 }) { if (input.length < headerSize || input.length > limits.maxPackageBytes) throw new Error("Animation package size is invalid"); if (!magic.every((byte, index) => input[index] === byte)) throw new Error("Animation package magic is invalid"); const view = new DataView(input.buffer, input.byteOffset, input.byteLength); if (view.getUint16(8, true) !== containerVersion) throw new Error("Animation container version is unsupported"); const length = view.getUint32(12, true); if (length !== input.length - headerSize) throw new Error("Animation package length is invalid"); const payload = input.slice(headerSize); const expected = input.slice(16, 48); const actual = sha256(payload); if (!actual.every((byte, index) => expected[index] === byte)) throw new Error("Animation package checksum is invalid"); return payload; }
