import { lexAnimation, type Token, type TokenKind } from "./lexer";
import type { AnimationProgram, ComponentNode, InputNode, KeyframeNode, MachineNode, ScalarValue, SceneNode, SourceSpan, TimelineNode, TrackNode, TransitionNode, Unit } from "./types";

class Parser {
  #index = 0; #depth = 0;
  constructor(readonly tokens: Token[], readonly maxDepth = 64) {}
  current() { return this.tokens[this.#index] ?? this.tokens[this.tokens.length - 1]!; }
  take(kind?: TokenKind, value?: string) { const token = this.current(); if (kind && token.kind !== kind || value && token.value !== value) throw new Error(`Expected ${value ?? kind}, found ${token.value || token.kind} at ${token.span.start.line}:${token.span.start.column}`); this.#index += 1; return token; }
  match(value: string) { if (this.current().value !== value) return false; this.#index += 1; return true; }
  identifier() { return this.take("identifier").value; }
  block<T>(read: () => T[]): { values: T[]; end: Token } { this.take("symbol", "{"); this.#depth += 1; if (this.#depth > this.maxDepth) throw new Error("Animation source exceeds maximum nesting"); const values = read(); const end = this.take("symbol", "}"); this.#depth -= 1; return { values, end }; }
  duration() { const token = this.take("number"); const match = /^(-?\d+(?:\.\d+)?)(ms|s)$/.exec(token.value); if (!match) throw new Error(`Expected duration at ${token.span.start.line}:${token.span.start.column}`); return (Number(match[1]) * (match[2] === "s" ? 1000 : 1)); }
  scalar(): ScalarValue { const token = this.take(); if (token.kind === "string") return { kind: "string", value: token.value }; if (token.kind === "color") return { kind: "color", value: token.value }; if (token.kind === "identifier" && (token.value === "true" || token.value === "false")) return { kind: "boolean", value: token.value === "true" }; if (token.kind === "number") { const match = /^(-?\d+(?:\.\d+)?)(ms|s|%|dp|sp|deg)?$/.exec(token.value); if (!match) throw new Error(`Invalid numeric value ${token.value}`); const rawUnit = match[2]; const unit: Unit = rawUnit === "%" ? "percent" : rawUnit === undefined ? "number" : rawUnit as Unit; const multiplier = rawUnit === "s" ? 1000 : 1; return { kind: "number", value: Number(match[1]) * multiplier, unit: rawUnit === "s" ? "ms" : unit }; } throw new Error(`Expected value at ${token.span.start.line}:${token.span.start.column}`); }
  input(): InputNode { const start = this.take("identifier", "input").span.start; const name = this.identifier(); this.take("symbol", ":"); const type = this.identifier() as InputNode["type"]; this.take("symbol", "="); const defaultValue = this.scalar(); const end = this.take("symbol", ";").span.end; return { name, type, defaultValue, span: { start, end } }; }
  component(): ComponentNode { const start = this.take("identifier", "component").span.start; const id = this.identifier(); const kind = this.identifier() as ComponentNode["kind"]; const properties: Record<string, ScalarValue> = {}; const { end } = this.block(() => { while (this.current().value !== "}") { const name = this.identifier(); this.take("symbol", ":"); properties[name] = this.scalar(); this.take("symbol", ";"); } return []; }); return { id, kind, properties, span: { start, end: end.span.end } }; }
  track(): TrackNode { const start = this.take("identifier", "track").span.start; const target = this.identifier(); const keyframes: KeyframeNode[] = []; const { end } = this.block(() => { while (this.current().value !== "}") { const frameStart = this.current().span.start; const timeMs = this.duration(); this.take("symbol", ":"); const value = this.scalar(); if (value.kind !== "number") throw new Error("Timeline keyframes must be numeric in language version 1"); let easing = "linear"; if (this.match("ease")) easing = this.identifier(); const frameEnd = this.take("symbol", ";").span.end; keyframes.push({ timeMs, value: value.value, easing, span: { start: frameStart, end: frameEnd } }); } return []; }); return { target, keyframes, span: { start, end: end.span.end } }; }
  timeline(): TimelineNode { const start = this.take("identifier", "timeline").span.start; const name = this.identifier(); const durationMs = this.duration(); const tracks: TrackNode[] = []; const { end } = this.block(() => { while (this.current().value !== "}") tracks.push(this.track()); return []; }); return { name, durationMs, tracks, span: { start, end: end.span.end } }; }
  machine(): MachineNode { const start = this.take("identifier", "machine").span.start; const name = this.identifier(); this.take("identifier", "initial"); const initialState = this.identifier(); const states: string[] = []; const transitions: TransitionNode[] = []; const { end } = this.block(() => { while (this.current().value !== "}") { if (this.current().value === "state") { this.take(); states.push(this.identifier()); this.take("symbol", ";"); continue; } const transitionStart = this.take("identifier", "transition").span.start; const from = this.identifier(); this.take("symbol", "->"); const to = this.identifier(); this.take("identifier", "on"); const event = this.identifier(); let timeline: string | undefined; let emittedEvent: string | undefined; if (this.match("play")) timeline = this.identifier(); if (this.match("emit")) emittedEvent = this.identifier(); const transitionEnd = this.take("symbol", ";").span.end; transitions.push({ from, to, event, timeline, emittedEvent, span: { start: transitionStart, end: transitionEnd } }); } return []; }); return { name, initialState, states, transitions, span: { start, end: end.span.end } }; }
  scene(): SceneNode { const start = this.take("identifier", "scene").span.start; const name = this.identifier(); const inputs: InputNode[] = []; const components: ComponentNode[] = []; const timelines: TimelineNode[] = []; const machines: MachineNode[] = []; let reducedMotionTimeline: string | undefined; const { end } = this.block(() => { while (this.current().value !== "}") { switch (this.current().value) { case "input": inputs.push(this.input()); break; case "component": components.push(this.component()); break; case "timeline": timelines.push(this.timeline()); break; case "machine": machines.push(this.machine()); break; case "reducedMotion": this.take(); this.take("symbol", ":"); reducedMotionTimeline = this.identifier(); this.take("symbol", ";"); break; default: throw new Error(`Unexpected scene declaration ${this.current().value}`); } } return []; }); return { name, inputs, components, timelines, machines, reducedMotionTimeline, span: { start, end: end.span.end } }; }
  program(): AnimationProgram { const start = this.take("identifier", "language").span.start; const version = this.take("number"); if (version.value !== "1") throw new Error(`Unsupported animation language version ${version.value}`); this.take("identifier", "package"); const packageName = this.identifier(); this.take("symbol", ";"); const scenes: SceneNode[] = []; while (this.current().kind !== "eof") scenes.push(this.scene()); const end = this.take("eof").span.end; return { languageVersion: 1, packageName, scenes, span: { start, end } }; }
}
export function parseAnimation(source: string) { return new Parser(lexAnimation(source)).program(); }
