import { compareVersions } from "../core/versioning";
import { decodeAnimationFlatbuffer, verifyAndUnwrapAnimationPackage } from "./binary";
import type { CompiledAnimation, RenderFrame, RenderNode, ScalarValue, SceneNode, TimelineNode } from "./types";

export type InterruptionPolicy = "replace" | "smoothlyRetarget" | "ignore";
export type RuntimeDiagnostics = { runtimeVersion: string; packageCompilerVersion: string; schemaVersion: number; renderer: string; requiredFeatures: string[]; packageBytes: number; loadMs: number; frames: number; lastEvaluationMs: number };
const scalar = (value: ScalarValue): string | number | boolean => value.value;
export function springProgress(timeMs: number, durationMs: number, stiffness = 410, damping = 30, mass = 1) { if (timeMs <= 0) return 0; let x = 0; let velocity = 0; const target = 1; const total = Math.min(timeMs, durationMs) / 1000; const step = 1 / 240; let elapsed = 0; while (elapsed < total) { const dt = Math.min(step, total - elapsed); const acceleration = (-stiffness * (x - target) - damping * velocity) / mass; velocity += acceleration * dt; x += velocity * dt; elapsed += dt; } return timeMs >= durationMs ? 1 : x; }
export function easingProgress(easing: string, progress: number, elapsedMs: number, durationMs: number) { const t = Math.max(0, Math.min(1, progress)); if (easing === "outCubic") return 1 - (1 - t) ** 3; if (easing === "inCubic") return t ** 3; if (easing === "inOutCubic") return t < 0.5 ? 4 * t ** 3 : 1 - (-2 * t + 2) ** 3 / 2; if (easing.startsWith("steps")) { const steps = Math.max(1, Number(easing.replace(/\D/g, "")) || 1); return Math.floor(t * steps) / steps; } if (easing === "spring") return springProgress(elapsedMs, durationMs); return t; }
function interpolate(timeline: TimelineNode, target: string, elapsed: number, retargetStart?: number) { const track = timeline.tracks.find((item) => item.target === target); if (!track?.keyframes.length) return undefined; const frames = retargetStart === undefined ? track.keyframes : [{ ...track.keyframes[0]!, timeMs: 0, value: retargetStart }, ...track.keyframes.filter((item) => item.timeMs > 0)]; const nextIndex = frames.findIndex((item) => item.timeMs >= elapsed); if (nextIndex === 0) return frames[0]!.value; if (nextIndex < 0) return frames.at(-1)!.value; const from = frames[nextIndex - 1]!; const to = frames[nextIndex]!; const duration = to.timeMs - from.timeMs; if (duration <= 0) return to.value; const progress = easingProgress(to.easing, (elapsed - from.timeMs) / duration, elapsed - from.timeMs, duration); return from.value + (to.value - from.value) * progress; }
function bindText(value: string, inputs: Record<string, string | number | boolean>) { return value.replace(/\$\{([A-Za-z_][A-Za-z0-9_]*)\}/g, (_match, name: string) => String(inputs[name] ?? "")); }

export class AnimationRuntime {
  readonly compiled: CompiledAnimation; readonly scene: SceneNode; readonly diagnostics: RuntimeDiagnostics; #timeline: TimelineNode | null = null; #startedAt = 0; #speed = 1; #direction: 1 | -1 = 1; #pausedAt: number | null = null; #inputs: Record<string, string | number | boolean>; #machines: Record<string, string>; #pendingEvents: { at: number; event: string }[] = []; #listeners = new Set<(event: string) => void>(); #lastFrame: RenderFrame | null = null; #retargetBase: Record<string, number> = {}; #reducedMotion: boolean;
  constructor(packageBytes: Uint8Array, options: { scene: string; runtimeVersion?: string; reducedMotion?: boolean; rendererName?: string; supportedFeatures?: ReadonlySet<string> }) {
    const before = performance.now(); const payload = verifyAndUnwrapAnimationPackage(packageBytes); this.compiled = decodeAnimationFlatbuffer(payload); const runtimeVersion = options.runtimeVersion ?? "0.1.0"; if (compareVersions(runtimeVersion, this.compiled.minimumRuntime) < 0) throw new Error(`Package requires runtime ${this.compiled.minimumRuntime}`); const supported = options.supportedFeatures ?? new Set(["animation.core", "animation.state-machine", "animation.host-view"]); const missing = this.compiled.requiredFeatures.filter((feature) => !supported.has(feature)); if (missing.length) throw new Error(`Runtime does not support required features: ${missing.join(", ")}`); const scene = this.compiled.scenes.find((item) => item.name === options.scene); if (!scene) throw new Error(`Scene not found: ${options.scene}`); this.scene = scene; this.#inputs = Object.fromEntries(scene.inputs.map((input) => [input.name, scalar(input.defaultValue)])); this.#machines = Object.fromEntries(scene.machines.map((machine) => [machine.name, machine.initialState])); this.#reducedMotion = options.reducedMotion ?? false; this.diagnostics = { runtimeVersion, packageCompilerVersion: this.compiled.compilerVersion, schemaVersion: this.compiled.schemaVersion, renderer: options.rendererName ?? "headless", requiredFeatures: this.compiled.requiredFeatures, packageBytes: packageBytes.length, loadMs: performance.now() - before, frames: 0, lastEvaluationMs: 0 };
  }
  onEvent(listener: (event: string) => void) { this.#listeners.add(listener); return () => this.#listeners.delete(listener); }
  setInput(name: string, value: string | number | boolean) { const input = this.scene.inputs.find((item) => item.name === name); if (!input) throw new Error(`Unknown input ${name}`); if ((input.type === "boolean" && typeof value !== "boolean") || (["number", "integer", "duration", "percentage", "angle"].includes(input.type) && typeof value !== "number") || (input.type === "string" && typeof value !== "string")) throw new Error(`Input ${name} received an incompatible value`); this.#inputs[name] = value; }
  play(name: string, nowMs = performance.now(), interruption: InterruptionPolicy = "smoothlyRetarget") { const requested = this.#reducedMotion && this.scene.reducedMotionTimeline ? this.scene.reducedMotionTimeline : name; const timeline = this.scene.timelines.find((item) => item.name === requested); if (!timeline) throw new Error(`Timeline not found: ${requested}`); if (this.#timeline && interruption === "ignore") return; this.#retargetBase = {}; if (this.#timeline && interruption === "smoothlyRetarget" && this.#lastFrame) for (const track of timeline.tracks) { const [componentId, property] = track.target.split("."); const current = this.#lastFrame.nodes.find((node) => node.id === componentId)?.properties[property ?? ""]; if (typeof current === "number") this.#retargetBase[track.target] = current; } this.#timeline = timeline; this.#startedAt = nowMs; this.#pausedAt = null; this.#direction = 1; }
  pause(nowMs = performance.now()) { if (this.#timeline && this.#pausedAt === null) this.#pausedAt = nowMs; }
  resume(nowMs = performance.now()) { if (this.#pausedAt !== null) { this.#startedAt += nowMs - this.#pausedAt; this.#pausedAt = null; } }
  reverse(nowMs = performance.now()) { if (!this.#timeline) return; const elapsed = this.elapsed(nowMs); this.#direction = this.#direction === 1 ? -1 : 1; this.#startedAt = nowMs - (this.#timeline.durationMs - elapsed) / this.#speed; }
  setSpeed(speed: number) { if (!Number.isFinite(speed) || speed <= 0 || speed > 16) throw new Error("Playback speed must be greater than zero and at most 16"); this.#speed = speed; }
  seek(timeMs: number, nowMs = performance.now()) { if (!this.#timeline) throw new Error("No timeline is active"); const clamped = Math.max(0, Math.min(this.#timeline.durationMs, timeMs)); this.#startedAt = nowMs - (this.#direction === 1 ? clamped : this.#timeline.durationMs - clamped) / this.#speed; return this.tick(nowMs); }
  send(machineName: string, event: string, nowMs = performance.now()) { const machine = this.scene.machines.find((item) => item.name === machineName); if (!machine) throw new Error(`Machine not found: ${machineName}`); const state = this.#machines[machineName]; const transition = machine.transitions.find((item) => item.from === state && item.event === event); if (!transition) return false; this.#machines[machineName] = transition.to; if (transition.timeline) { this.play(transition.timeline, nowMs); if (transition.emittedEvent) this.#pendingEvents.push({ at: nowMs + (this.#timeline?.durationMs ?? 0) / this.#speed, event: transition.emittedEvent }); } else if (transition.emittedEvent) this.emit(transition.emittedEvent); return true; }
  elapsed(nowMs: number) { if (!this.#timeline) return 0; const clock = this.#pausedAt ?? nowMs; const raw = Math.max(0, (clock - this.#startedAt) * this.#speed); const value = this.#direction === 1 ? raw : this.#timeline.durationMs - raw; return Math.max(0, Math.min(this.#timeline.durationMs, value)); }
  emit(event: string) { for (const listener of this.#listeners) listener(event); }
  tick(nowMs = performance.now()) {
    const before = performance.now(); const elapsed = this.elapsed(nowMs); const nodes: RenderNode[] = this.scene.components.map((component) => { const properties = Object.fromEntries(Object.entries(component.properties).map(([name, value]) => [name, value.kind === "string" ? bindText(value.value, this.#inputs) : scalar(value)])); if (this.#timeline) for (const track of this.#timeline.tracks.filter((item) => item.target.startsWith(`${component.id}.`))) { const property = track.target.slice(component.id.length + 1); const value = interpolate(this.#timeline, track.target, elapsed, this.#retargetBase[track.target]); if (value !== undefined) properties[property] = value; } return { id: component.id, kind: component.kind, properties }; });
    const emittedEvents = this.#pendingEvents.filter((item) => item.at <= nowMs).map((item) => item.event); this.#pendingEvents = this.#pendingEvents.filter((item) => item.at > nowMs); for (const event of emittedEvents) this.emit(event); const frame: RenderFrame = { scene: this.scene.name, timeMs: elapsed, nodes, activeStateMachines: { ...this.#machines }, emittedEvents }; this.#lastFrame = frame; this.diagnostics.frames += 1; this.diagnostics.lastEvaluationMs = performance.now() - before; return frame;
  }
  get lastFrame() { return this.#lastFrame; }
}
