import { createHash } from "node:crypto";
import { put } from "@vercel/blob";
import { desc } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getDb, hasDatabase } from "@harborline/backend/db"; import { portableExports } from "@harborline/backend/schema"; import { getStudioUser } from "@/lib/auth"; import { createPortableBackup } from "@/lib/portable-backup";
export const maxDuration = 300; export const runtime = 'nodejs';
export async function GET() { const viewer = await getStudioUser(); if (!viewer || viewer.role !== 'admin') return NextResponse.json({ error: { code: 'forbidden', message: 'Admin access required' } }, { status: 403 }); if (!hasDatabase()) return NextResponse.json({ data: [], meta: { apiVersion: '1' } }); const data = await getDb().select().from(portableExports).orderBy(desc(portableExports.createdAt)).limit(20); return NextResponse.json({ data, meta: { apiVersion: '1' } }); }
export async function POST(request: Request) { const viewer = await getStudioUser(); if (!viewer || viewer.role !== 'admin') return NextResponse.json({ error: { code: 'forbidden', message: 'Admin access required' } }, { status: 403 }); if (!hasDatabase() || !process.env.BLOB_READ_WRITE_TOKEN) return NextResponse.json({ error: { code: 'service_not_configured', message: 'Postgres and Vercel Blob are required for Studio exports. The CLI can export directly to local disk.' } }, { status: 503 }); const parsed = z.object({ passphrase: z.string().min(14).max(256), includeMedia: z.boolean().default(true) }).safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: { code: 'invalid_request', message: 'Use a passphrase of at least 14 characters.' } }, { status: 400 }); try { const backup = await createPortableBackup({ passphrase: parsed.data.passphrase, includeMedia: parsed.data.includeMedia }); const filename = `backups/harborline-${new Date().toISOString().replaceAll(':', '-')}.hlnbackup`; const blob = await put(filename, backup.buffer, { access: 'private', addRandomSuffix: true, contentType: 'application/octet-stream' }); const [record] = await getDb().insert(portableExports).values({ blobUrl: blob.url, pathname: blob.pathname, checksumSha256: createHash('sha256').update(backup.buffer).digest('hex'), size: backup.buffer.length, createdByClerkId: viewer.id, expiresAt: new Date(Date.now() + 30 * 86_400_000) }).returning(); return NextResponse.json({ data: { ...record, downloadUrl: `/api/v1/studio/exports/${record.id}/download` }, meta: { apiVersion: '1', passphraseStored: false } }, { status: 201 }); } catch (error) { console.error(error); return NextResponse.json({ error: { code: 'export_failed', message: error instanceof Error ? error.message : 'Portable export failed' } }, { status: 500 }); } }
