import type { EmployeeEligibility } from "@harborline/contracts";
import { useCallback, useEffect, useState } from "react";
import { Linking, Platform, Pressable, StyleSheet, Text, View } from "react-native";
import { authenticatedRequest } from "@/lib/api";
import { deviceStorage } from "@/lib/storage";
import { useAppTheme } from "@/providers/theme-provider";

const destination = "njcourier-employee:///v1/dashboard";
const pendingKey = "njcourier:employee:pending-link";

export function EmployeeHandoff({ getToken }: { getToken: () => Promise<string | null> }) {
  const { colors } = useAppTheme(); const [eligibility, setEligibility] = useState<EmployeeEligibility | null>(null); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true); const [showInstall, setShowInstall] = useState(false);
  const refresh = useCallback(async () => { setLoading(true); try { const token = await getToken(); if (!token) throw new Error("Sign in to check employee access."); setEligibility(await authenticatedRequest("/api/v1/employee/eligibility", token)); setNotice(""); } catch (error) { setNotice(error instanceof Error ? error.message : "Employee access could not be checked."); } finally { setLoading(false); } }, [getToken]);
  useEffect(() => { const timer = setTimeout(() => void refresh(), 0); return () => clearTimeout(timer); }, [refresh]);
  async function openEmployeeApp() { await deviceStorage.setItem(pendingKey, destination); try { const installed = await Linking.canOpenURL(destination); if (installed) { await Linking.openURL(destination); return; } } catch { /* installation guidance below */ } setShowInstall(true); setNotice("This action requires the separate Employee App. The intended destination is preserved on this device."); }
  async function requestAccess() { try { const token = await getToken(); if (!token) throw new Error("Sign in to request access."); await authenticatedRequest("/api/v1/employee/access-requests", token, { method: "POST", body: JSON.stringify({ capability: "employee:access", sourceApp: "reader", intendedDestination: destination, reason: "Employee tools entry from the reader app" }) }); setNotice("Access request submitted. Installation guidance will become useful after approval."); } catch (error) { setNotice(error instanceof Error ? error.message : "Access request failed."); } }
  const installUrl = Platform.OS === "ios" ? eligibility?.install.ios ?? eligibility?.install.internal : eligibility?.install.android ?? eligibility?.install.internal;
  return <View style={[styles.card, { borderColor: colors.line, backgroundColor: colors.surface }]}><Text style={[styles.title, { color: colors.ink }]}>Employee tools</Text><Text style={{ color: colors.muted, lineHeight: 20 }}>Administrative and newsroom operations live in the separate, permission-gated Employee App.</Text>{loading ? <Text style={{ color: colors.muted }}>Checking access…</Text> : eligibility?.eligible ? <Pressable onPress={() => void openEmployeeApp()} style={[styles.button, { backgroundColor: colors.brandNavy }]}><Text style={{ color: colors.onBrand, fontWeight: "900" }}>Open Employee App</Text></Pressable> : <Pressable onPress={() => void requestAccess()} style={[styles.button, { backgroundColor: colors.brandNavy }]}><Text style={{ color: colors.onBrand, fontWeight: "900" }}>Request employee access</Text></Pressable>}{showInstall ? installUrl ? <Pressable onPress={() => void Linking.openURL(installUrl)} style={[styles.secondary, { borderColor: colors.line }]}><Text style={{ color: colors.ink, fontWeight: "900" }}>Open configured installation page</Text></Pressable> : <Text style={{ color: colors.muted }}>An App Store, Play Store, beta, or managed-distribution URL has not been configured. Ask an administrator for the approved installation path.</Text> : null}{notice ? <Text accessibilityLiveRegion="polite" style={{ color: colors.muted }}>{notice}</Text> : null}<Pressable onPress={() => void refresh()}><Text style={{ color: colors.blue, fontWeight: "800" }}>Recheck access and installation</Text></Pressable></View>;
}
const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 10, padding: 15, gap: 9, marginVertical: 10 }, title: { fontSize: 18, fontWeight: "900" }, button: { minHeight: 48, borderRadius: 8, alignItems: "center", justifyContent: "center" }, secondary: { minHeight: 46, borderRadius: 8, borderWidth: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 12 } });
