import { createHash, timingSafeEqual } from "node:crypto";
import { canonicalJson } from "./canonical";
import { signReceipt, type SigningKeyProvider } from "./crypto-node";
import { verifySignedReceipt } from "./verifier";
import type { Activation, ApplicationIdentity, Customer, IdempotencyRecord, Installation, LicenseAudit, LicenseKind, LicenseRecord, LicensedApplication, OfflineLease, Organization, Plan, Product, ReceiptClaims, SignedReceipt, UsageReport } from "./types";

type CreateLicenseInput = { organizationId: string; customerId: string; productId: string; applicationId: string; planId: string; kind: Exclude<LicenseKind, "first_party">; startsAt?: Date; expiresAt?: Date; idempotencyKey: string; actor: string };
type ActivateInput = { licenseKey: string; applicationIdentity: ApplicationIdentity; pseudonymousDeviceId: string; idempotencyKey: string };
const id = (prefix: string) => `${prefix}_${crypto.randomUUID()}`;
function identityEquals(a: ApplicationIdentity, b: ApplicationIdentity) { return a.applicationId === b.applicationId && a.platform === b.platform && a.environment === b.environment && a.buildId === b.buildId && a.bundleOrPackageId === b.bundleOrPackageId && a.signingIdentity === b.signingIdentity && a.host === b.host; }

export class ReferenceLicenseService {
  readonly organizations = new Map<string, Organization>(); readonly customers = new Map<string, Customer>(); readonly products = new Map<string, Product>(); readonly applications = new Map<string, LicensedApplication>(); readonly plans = new Map<string, Plan>(); readonly licenses = new Map<string, LicenseRecord>(); readonly installations = new Map<string, Installation>(); readonly activations: Activation[] = []; readonly offlineLeases: OfflineLease[] = []; readonly audits: LicenseAudit[] = []; readonly usageReports: UsageReport[] = []; readonly #idempotency = new Map<string, IdempotencyRecord>();
  constructor(readonly config: { issuer: string; audience: string; keyPepper: string; keys: SigningKeyProvider; now?: () => Date }) { if (config.keyPepper.length < 16) throw new Error("License key pepper must be at least 16 characters"); }
  now() { return this.config.now?.() ?? new Date(); }
  registerOrganization(record: Organization) { this.organizations.set(record.id, record); }
  registerCustomer(record: Customer) { this.customers.set(record.id, record); }
  registerProduct(record: Product) { this.products.set(record.id, record); }
  registerApplication(record: LicensedApplication) { this.applications.set(record.id, record); }
  registerPlan(record: Plan) { this.plans.set(record.id, record); }
  #audit(actor: string, action: string, targetId: string, metadata: Record<string, unknown> = {}) { this.audits.push(Object.freeze({ id: id("audit"), at: this.now().toISOString(), actor, action, targetId, metadata })); }
  #hashKey(key: string) { return createHash("sha256").update(this.config.keyPepper).update("\0").update(key).digest("hex"); }
  #idempotent<T>(scope: string, key: string, input: unknown, operation: () => T): T {
    const index = `${scope}:${key}`; const requestHash = createHash("sha256").update(canonicalJson(input)).digest("hex"); const existing = this.#idempotency.get(index);
    if (existing) { if (existing.requestHash !== requestHash) throw new Error("Idempotency key was reused with different input"); return existing.response as T; }
    const response = operation(); this.#idempotency.set(index, { scope, key, requestHash, response, createdAt: this.now().toISOString() }); return response;
  }
  createLicense(input: CreateLicenseInput) {
    return this.#idempotent("create-license", input.idempotencyKey, input, () => {
      if (!this.organizations.has(input.organizationId) || !this.customers.has(input.customerId) || !this.products.has(input.productId) || !this.applications.has(input.applicationId) || !this.plans.has(input.planId)) throw new Error("License references an unknown organization, customer, product, application, or plan");
      const rawKey = `pl_${crypto.randomUUID().replaceAll("-", "")}${crypto.randomUUID().replaceAll("-", "")}`; const record: LicenseRecord = { id: id("lic"), version: 1, organizationId: input.organizationId, customerId: input.customerId, productId: input.productId, applicationId: input.applicationId, planId: input.planId, kind: input.kind, status: "active", keyHash: this.#hashKey(rawKey), startsAt: (input.startsAt ?? this.now()).toISOString(), expiresAt: input.expiresAt?.toISOString() ?? null, createdAt: this.now().toISOString() };
      this.licenses.set(record.id, record); this.#audit(input.actor, "license.created", record.id, { kind: record.kind }); return { license: { ...record, keyHash: null }, licenseKey: rawKey };
    });
  }
  createFirstPartyEntitlement(input: { organizationId: string; customerId: string; productId: string; applicationId: string; planId: string; actor: string }) {
    const app = this.applications.get(input.applicationId); if (!app || !app.identities.length) throw new Error("First-party application identities must be registered first");
    const record: LicenseRecord = { id: id("lic_first"), version: 1, organizationId: input.organizationId, customerId: input.customerId, productId: input.productId, applicationId: input.applicationId, planId: input.planId, kind: "first_party", status: "active", keyHash: null, startsAt: this.now().toISOString(), expiresAt: null, createdAt: this.now().toISOString() };
    this.licenses.set(record.id, record); this.#audit(input.actor, "first_party_entitlement.created", record.id, { identities: app.identities }); return { ...record };
  }
  #licenseByKey(raw: string) { const actual = Buffer.from(this.#hashKey(raw)); return [...this.licenses.values()].find((license) => license.keyHash && actual.length === Buffer.byteLength(license.keyHash) && timingSafeEqual(actual, Buffer.from(license.keyHash))); }
  #assertUsable(license: LicenseRecord) { const now = this.now().getTime(); if (license.status !== "active") throw new Error(`License is ${license.status}`); if (Date.parse(license.startsAt) > now) throw new Error("License is not active yet"); if (license.expiresAt && Date.parse(license.expiresAt) <= now) throw new Error("License is expired"); const organization = this.organizations.get(license.organizationId); if (organization?.status !== "active") throw new Error("Organization is suspended"); }
  #assertIdentity(license: LicenseRecord, identity: ApplicationIdentity) { const app = this.applications.get(license.applicationId); if (!app?.identities.some((candidate) => identityEquals(candidate, identity))) throw new Error("Application identity is not approved for this license"); }
  async #issue(license: LicenseRecord, installation: Installation, offline: boolean) {
    this.#assertUsable(license); const plan = this.plans.get(license.planId); if (!plan) throw new Error("License plan is unavailable"); const now = this.now(); const leaseSeconds = offline ? plan.offlineLeaseSeconds : plan.leaseSeconds; const claims: ReceiptClaims = { receiptVersion: 1, licenseId: license.id, licenseVersion: license.version, licenseKind: license.kind, issuer: this.config.issuer, audience: this.config.audience, organizationId: license.organizationId, productId: license.productId, application: installation.applicationIdentity, entitledFeatures: [...plan.featureIds].sort(), installationId: installation.id, issuedAt: now.toISOString(), notBefore: now.toISOString(), leaseExpiresAt: new Date(now.getTime() + leaseSeconds * 1000).toISOString(), graceEndsAt: new Date(now.getTime() + (leaseSeconds + plan.graceSeconds) * 1000).toISOString(), offline, usageLimits: {} }; return signReceipt(claims, this.config.keys);
  }
  async activate(input: ActivateInput) {
    const result = this.#idempotent("activate", input.idempotencyKey, input, () => {
      const license = this.#licenseByKey(input.licenseKey); if (!license || license.kind === "first_party") throw new Error("License key is invalid"); this.#assertUsable(license); this.#assertIdentity(license, input.applicationIdentity); const plan = this.plans.get(license.planId); if (!plan) throw new Error("Plan unavailable"); const active = [...this.installations.values()].filter((item) => item.licenseId === license.id && !item.deactivatedAt); if (active.length >= plan.deviceLimit) throw new Error("Device or seat limit reached"); const now = this.now().toISOString(); const installation: Installation = { id: id("inst"), licenseId: license.id, applicationIdentity: input.applicationIdentity, pseudonymousDeviceId: input.pseudonymousDeviceId, activatedAt: now, lastSeenAt: now }; this.installations.set(installation.id, installation); const activation: Activation = { id: id("act"), licenseId: license.id, installationId: installation.id, status: "active", createdAt: now }; this.activations.push(activation); this.#audit("license-client", "installation.activated", installation.id, { licenseId: license.id }); return { license, installation, activation };
    });
    return { installationId: result.installation.id, receipt: await this.#issue(result.license, result.installation, false) };
  }
  async issueFirstPartyReceipt(licenseId: string, identity: ApplicationIdentity, installationId: string) { const license = this.licenses.get(licenseId); if (!license || license.kind !== "first_party") throw new Error("First-party entitlement not found"); this.#assertIdentity(license, identity); const now = this.now().toISOString(); let installation = this.installations.get(installationId); if (!installation) { installation = { id: installationId, licenseId, applicationIdentity: identity, pseudonymousDeviceId: installationId, activatedAt: now, lastSeenAt: now }; this.installations.set(installationId, installation); } else if (!identityEquals(installation.applicationIdentity, identity)) throw new Error("Installation identity changed"); this.#audit("first-party-identity-service", "first_party_receipt.issued", installationId, { licenseId }); return this.#issue(license, installation, false); }
  async refreshOnlineLease(installationId: string) { const installation = this.installations.get(installationId); if (!installation || installation.deactivatedAt) throw new Error("Installation is not active"); installation.lastSeenAt = this.now().toISOString(); const license = this.licenses.get(installation.licenseId); if (!license) throw new Error("License not found"); return this.#issue(license, installation, false); }
  async issueOfflineLease(installationId: string) { const installation = this.installations.get(installationId); if (!installation || installation.deactivatedAt) throw new Error("Installation is not active"); const license = this.licenses.get(installation.licenseId); if (!license) throw new Error("License not found"); const receipt = await this.#issue(license, installation, true); const claims = JSON.parse(Buffer.from(receipt.payload, "base64url").toString("utf8")) as ReceiptClaims; const lease: OfflineLease = { id: id("lease"), licenseId: license.id, installationId, expiresAt: claims.leaseExpiresAt, graceEndsAt: claims.graceEndsAt, receipt }; this.offlineLeases.push(lease); this.#audit("license-client", "offline_lease.issued", lease.id, { installationId }); return lease;
  }
  deactivateInstallation(installationId: string, actor = "license-client") { const installation = this.installations.get(installationId); if (!installation) return false; installation.deactivatedAt = this.now().toISOString(); const activation = [...this.activations].reverse().find((item) => item.installationId === installationId && item.status === "active"); if (activation) activation.status = "deactivated"; this.#audit(actor, "installation.deactivated", installationId); return true; }
  transferSeat(installationId: string, newPseudonymousDeviceId: string, actor: string) { const installation = this.installations.get(installationId); if (!installation || installation.deactivatedAt) throw new Error("Installation is unavailable"); installation.pseudonymousDeviceId = newPseudonymousDeviceId; const activation = [...this.activations].reverse().find((item) => item.installationId === installationId); if (activation) activation.status = "transferred"; this.#audit(actor, "seat.transferred", installationId); }
  #changeStatus(licenseId: string, status: LicenseRecord["status"], actor: string) { const license = this.licenses.get(licenseId); if (!license) throw new Error("License not found"); license.status = status; license.version += 1; if (status === "revoked") license.revokedAt = this.now().toISOString(); if (status === "suspended") license.suspendedAt = this.now().toISOString(); this.#audit(actor, `license.${status}`, licenseId); return { ...license, keyHash: null }; }
  revokeLicense(id: string, actor: string) { return this.#changeStatus(id, "revoked", actor); }
  suspendLicense(id: string, actor: string) { return this.#changeStatus(id, "suspended", actor); }
  restoreLicense(id: string, actor: string) { return this.#changeStatus(id, "active", actor); }
  rotateSigningKey(actor: string) { return this.config.keys.rotate().then((key) => { this.#audit(actor, "signing_key.rotated", key.id); return key; }); }
  activationHistory(licenseId: string) { return this.activations.filter((item) => item.licenseId === licenseId).map((item) => ({ ...item })); }
  auditHistory(targetId?: string) { return this.audits.filter((item) => !targetId || item.targetId === targetId).map((item) => ({ ...item })); }
  receiveSignedUsageReport(report: UsageReport, verifyReport: (report: UsageReport) => boolean) { if (!verifyReport(report)) throw new Error("Usage report signature is invalid"); this.usageReports.push(Object.freeze({ ...report, counters: { ...report.counters } })); this.#audit("license-client", "usage_report.received", report.installationId, { periodStart: report.periodStart, periodEnd: report.periodEnd }); }
  async publicVerificationKeys() { return this.config.keys.publicKeys(); }
  async validateEntitlement(receipt: SignedReceipt, expected: { application: ApplicationIdentity; productId: string }) { const revoked = new Set([...this.licenses.values()].filter((license) => license.status === "revoked").map((license) => license.id)); return verifySignedReceipt(receipt, await this.publicVerificationKeys(), { issuer: this.config.issuer, audience: this.config.audience, productId: expected.productId, application: expected.application, knownRevokedLicenseIds: revoked, allowGrace: true, now: this.now() }); }
  async retrieveEntitledFeatures(receipt: SignedReceipt, expected: { application: ApplicationIdentity; productId: string }) { const result = await this.validateEntitlement(receipt, expected); if (!result.ok) throw new Error(result.message); return result.claims.entitledFeatures; }
}
