export type LicenseKind = "commercial" | "trial" | "development" | "first_party";
export type LicenseStatus = "active" | "suspended" | "revoked" | "expired";
export type Environment = "development" | "preview" | "staging" | "production";
export type ApplicationIdentity = {
  applicationId: string;
  platform: "web" | "ios" | "android" | "tvos" | "androidtv" | "roku" | "node";
  environment: Environment;
  buildId: string;
  bundleOrPackageId?: string;
  signingIdentity?: string;
  host?: string;
};
export type ReceiptClaims = {
  receiptVersion: 1;
  licenseId: string;
  licenseVersion: number;
  licenseKind: LicenseKind;
  issuer: string;
  audience: string;
  organizationId: string;
  productId: string;
  application: ApplicationIdentity;
  entitledFeatures: string[];
  installationId: string;
  issuedAt: string;
  notBefore: string;
  leaseExpiresAt: string;
  graceEndsAt: string;
  offline: boolean;
  usageLimits: Record<string, number>;
};
export type SignedReceipt = { keyId: string; algorithm: "Ed25519"; payload: string; signature: string };
export type ReceiptErrorCode = "malformed" | "signature_invalid" | "unknown_key" | "wrong_issuer" | "wrong_audience" | "wrong_application" | "wrong_environment" | "wrong_product" | "not_yet_valid" | "expired" | "revoked" | "unsupported_version" | "server_unavailable";
export type ReceiptValidation = { ok: true; claims: ReceiptClaims; inGrace: boolean } | { ok: false; code: ReceiptErrorCode; message: string };

export type Organization = { id: string; name: string; status: "active" | "suspended" };
export type Customer = { id: string; organizationId: string; externalId?: string; email?: string };
export type Product = { id: string; name: string; featureIds: string[] };
export type LicensedApplication = { id: string; organizationId: string; productId: string; identities: ApplicationIdentity[] };
export type Plan = { id: string; productId: string; featureIds: string[]; seatLimit: number; deviceLimit: number; leaseSeconds: number; offlineLeaseSeconds: number; graceSeconds: number };
export type LicenseRecord = { id: string; version: number; organizationId: string; customerId: string; productId: string; applicationId: string; planId: string; kind: LicenseKind; status: LicenseStatus; keyHash: string | null; startsAt: string; expiresAt: string | null; suspendedAt?: string; revokedAt?: string; createdAt: string };
export type Seat = { id: string; licenseId: string; assigneeId?: string; transferredAt?: string };
export type Installation = { id: string; licenseId: string; applicationIdentity: ApplicationIdentity; pseudonymousDeviceId: string; activatedAt: string; deactivatedAt?: string; lastSeenAt: string };
export type Activation = { id: string; licenseId: string; installationId: string; status: "active" | "deactivated" | "transferred"; createdAt: string };
export type OfflineLease = { id: string; licenseId: string; installationId: string; expiresAt: string; graceEndsAt: string; receipt: SignedReceipt };
export type SigningKeyRecord = { id: string; algorithm: "Ed25519"; publicKeyPem: string; status: "active" | "retired"; createdAt: string; retiredAt?: string };
export type LicenseAudit = { id: string; at: string; actor: string; action: string; targetId: string; metadata: Record<string, unknown> };
export type WebhookRegistration = { id: string; organizationId: string; url: string; secretReference: string; events: string[]; active: boolean };
export type IdempotencyRecord = { scope: string; key: string; requestHash: string; response: unknown; createdAt: string };
export type UsageReport = { installationId: string; periodStart: string; periodEnd: string; counters: Record<string, number>; signature: string };
