import { ArrowUpRight, Eye, MousePointerClick, Users } from "lucide-react";
import { StudioGate } from "@/components/studio/studio-gate";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";

export default function AnalyticsPage() {
  return <StudioGate><div><h1 className="text-3xl font-bold tracking-tight">Analytics</h1><p className="mt-1 text-sm text-muted-foreground">Live editorial signals, not vanity metrics.</p><div className="mt-7 grid gap-4 sm:grid-cols-3"><Metric icon={<Users />} title="Readers" value="38.4k" delta="+12.8%" /><Metric icon={<Eye />} title="Story views" value="71.2k" delta="+9.4%" /><Metric icon={<MousePointerClick />} title="Newsletter CTR" value="42.6%" delta="+3.1%" /></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.3fr_0.7fr]"><Card><CardHeader><CardTitle>Audience, last 24 hours</CardTitle><CardDescription>Hourly active readers across web and API clients.</CardDescription></CardHeader><CardContent><div className="flex h-64 items-end gap-2 border-b border-l p-4">{[24,31,28,44,39,53,68,61,79,72,88,64,75,92,84,100,91,78,70,62,55,49,37,29].map((height, index) => <div key={index} className="flex-1 rounded-t-sm bg-primary/75" style={{ height: `${height}%` }} />)}</div></CardContent></Card><Card><CardHeader><CardTitle>Top stories</CardTitle></CardHeader><CardContent className="space-y-5">{[["Waterfront resilience plan","10.4k",92],["Coastal storm watch","8.8k",78],["Housing audit","6.1k",55],["Harbor Hawks playoffs","3.9k",34]].map(([title,views,progress]) => <div key={String(title)}><div className="mb-2 flex justify-between gap-3 text-sm"><p className="font-medium">{title}</p><p className="text-muted-foreground">{views}</p></div><Progress value={Number(progress)} /></div>)}</CardContent></Card></div></div></StudioGate>;
}
function Metric({ icon, title, value, delta }: { icon: React.ReactNode; title: string; value: string; delta: string }) { return <Card><CardContent className="flex items-start justify-between p-5"><div><p className="text-sm text-muted-foreground">{title}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-1 flex items-center text-xs text-emerald-400">{delta} <ArrowUpRight className="size-3" /></p></div><span className="rounded-md bg-primary/10 p-2 text-primary [&_svg]:size-4">{icon}</span></CardContent></Card>; }
