import { useAuth } from "@clerk/expo";
import { Link, router } from "expo-router";
import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Card, Label, Screen, StateCard } from "@/components/screen";
import { employeeRequest } from "@/lib/api";
import { useEmployee, type EmployeeChannel } from "@/providers/employee-provider";
import { useAppTheme } from "@/providers/theme-provider";

type DirectoryEntry = { clerkId: string; displayName: string; title: string | null; avatarUrl: string | null };
export default function ChatListScreen() {
  const employee = useEmployee(); const { getToken } = useAuth(); const { colors } = useAppTheme(); const [creating, setCreating] = useState(false); const [name, setName] = useState(""); const [kind, setKind] = useState<"public" | "private">("public"); const [directory, setDirectory] = useState<DirectoryEntry[]>([]); const [notice, setNotice] = useState("");
  async function request<T>(path: string, init?: RequestInit) { const token = await getToken(); if (!token) throw new Error("Session expired."); return employeeRequest<T>(path, token, init); }
  async function createChannel() { try { const channel = await request<EmployeeChannel>("/api/v1/employee/chat/channels", { method: "POST", body: JSON.stringify({ kind, name, memberClerkIds: [] }) }); setCreating(false); setName(""); await employee.refresh(); router.push({ pathname: "/chat/[id]", params: { id: channel.id } }); } catch (error) { setNotice(error instanceof Error ? error.message : "Channel could not be created."); } }
  async function loadDirectory() { try { setDirectory(await request("/api/v1/employee/directory")); } catch (error) { setNotice(error instanceof Error ? error.message : "Directory unavailable."); } }
  async function directMessage(person: DirectoryEntry) { try { const channel = await request<EmployeeChannel>("/api/v1/employee/chat/channels", { method: "POST", body: JSON.stringify({ kind: "direct", name: person.displayName, memberClerkIds: [person.clerkId] }) }); await employee.refresh(); router.push({ pathname: "/chat/[id]", params: { id: channel.id } }); } catch (error) { setNotice(error instanceof Error ? error.message : "Conversation could not be opened."); } }
  if (!employee.has("chat:read")) return <Screen title="Communication"><StateCard title="Chat access required" body="Your account does not currently have the internal-chat capability. You can request it from Access Status." /></Screen>;
  return <Screen eyebrow="INTERNAL COMMUNICATION" title="Channels" refresh={() => void employee.refresh()}>{notice ? <StateCard title="Status" body={notice} /> : null}<View style={styles.toolbar}>{employee.has("chat:manage") ? <Pressable onPress={() => setCreating((value) => !value)}><Text style={{ color: colors.brand, fontWeight: "900" }}>{creating ? "Cancel" : "New channel"}</Text></Pressable> : null}{employee.has("chat:write") ? <Pressable onPress={() => void loadDirectory()}><Text style={{ color: colors.brand, fontWeight: "900" }}>New direct message</Text></Pressable> : null}</View>{creating ? <Card><Label>Create channel</Label><View style={styles.toolbar}>{(["public", "private"] as const).map((value) => <Pressable key={value} onPress={() => setKind(value)} style={[styles.chip, { borderColor: colors.line, backgroundColor: kind === value ? colors.brandSoft : colors.surface }]}><Text style={{ color: colors.ink, fontWeight: "800", textTransform: "capitalize" }}>{value}</Text></Pressable>)}</View><TextInput value={name} onChangeText={setName} placeholder="Channel name" style={[styles.input, { borderColor: colors.line, color: colors.ink }]} /><Pressable disabled={!name.trim()} onPress={() => void createChannel()} style={[styles.button, { backgroundColor: colors.brand }, !name.trim() && { opacity: 0.4 }]}><Text style={{ color: colors.onBrand, fontWeight: "900" }}>Create channel</Text></Pressable></Card> : null}{directory.length ? <Card><Label>Start a direct message</Label>{directory.filter((person) => person.clerkId !== employee.data?.viewer.id).map((person) => <Pressable key={person.clerkId} onPress={() => void directMessage(person)} style={[styles.person, { borderBottomColor: colors.line }]}><View><Text style={{ color: colors.ink, fontWeight: "900" }}>{person.displayName}</Text>{person.title ? <Text style={{ color: colors.muted }}>{person.title}</Text> : null}</View><Text style={{ color: colors.brand, fontWeight: "900" }}>Message</Text></Pressable>)}</Card> : null}{employee.data?.channels.length ? employee.data.channels.map((channel) => <Link key={channel.id} href={{ pathname: "/chat/[id]", params: { id: channel.id } }} asChild><Pressable><Card><View style={styles.row}><View style={styles.copy}><Text style={[styles.name, { color: colors.ink }]}>{channel.kind === "public" ? "# " : ""}{channel.name}</Text>{channel.topic ? <Text numberOfLines={2} style={{ color: colors.muted }}>{channel.topic}</Text> : null}</View>{channel.unread ? <Text style={[styles.badge, { backgroundColor: colors.accent, color: colors.ink }]}>{channel.unread}</Text> : null}</View></Card></Pressable></Link>) : <StateCard title="No conversations yet" body="A channel manager can create the first internal channel. No development fixtures are shown in production paths." />}</Screen>;
}
const styles = StyleSheet.create({ toolbar: { flexDirection: "row", flexWrap: "wrap", gap: 16 }, row: { flexDirection: "row", alignItems: "center", gap: 10 }, copy: { flex: 1 }, name: { fontSize: 17, fontWeight: "900" }, badge: { minWidth: 25, height: 25, borderRadius: 13, textAlign: "center", paddingTop: 3, fontWeight: "900" }, chip: { borderWidth: 1, borderRadius: 20, paddingHorizontal: 13, paddingVertical: 8 }, input: { borderWidth: 1, borderRadius: 8, minHeight: 48, paddingHorizontal: 12 }, button: { minHeight: 48, borderRadius: 8, alignItems: "center", justifyContent: "center" }, person: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12, paddingVertical: 11, borderBottomWidth: StyleSheet.hairlineWidth } });
