import { useAuth } from "@clerk/expo";
import { useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useRef, useState } from "react";
import { AppState, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Card, Screen, StateCard } from "@/components/screen";
import { employeeRequest } from "@/lib/api";
import { useEmployee } from "@/providers/employee-provider";
import { useAppTheme } from "@/providers/theme-provider";

type Message = { id: string; channelId: string; authorClerkId: string; authorName: string; body: string; replyToId: string | null; isPinned: boolean; editedAt: string | null; deletedAt: string | null; createdAt: string };
export default function ConversationScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { getToken } = useAuth(); const employee = useEmployee(); const { colors } = useAppTheme(); const channel = employee.data?.channels.find((item) => item.id === id);
  const [messages, setMessages] = useState<Message[]>([]); const [body, setBody] = useState(""); const [search, setSearch] = useState(""); const [notice, setNotice] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [replyTo, setReplyTo] = useState<Message | null>(null); const cursor = useRef<string | null>(null);
  const request = useCallback(async <T,>(path: string, init?: RequestInit) => { const token = await getToken(); if (!token) throw new Error("Your session expired."); return employeeRequest<T>(path, token, init); }, [getToken]);
  const load = useCallback(async (replace = false) => { if (!id) return; try { const query = replace || !cursor.current ? `?limit=100${search ? `&q=${encodeURIComponent(search)}` : ""}` : `?after=${encodeURIComponent(cursor.current)}`; const next = await request<Message[]>(`/api/v1/employee/chat/channels/${id}/messages${query}`); setMessages((current) => replace || !cursor.current ? next : [...current, ...next.filter((message) => !current.some((item) => item.id === message.id))]); const latest = next.at(-1)?.createdAt; if (latest) cursor.current = latest; if (replace) await request(`/api/v1/employee/chat/channels/${id}/read`, { method: "POST" }); setNotice(null); } catch (error) { setNotice(error instanceof Error ? error.message : "Conversation unavailable."); } finally { setLoading(false); } }, [id, request, search]);
  useEffect(() => { cursor.current = null; void load(true); }, [load]);
  useEffect(() => { const timer = setInterval(() => { if (AppState.currentState === "active" && !search) void load(false); }, 3000); return () => clearInterval(timer); }, [load, search]);
  async function send() { const clean = body.trim(); if (!clean || !id) return; setBody(""); try { const created = await request<Message>(`/api/v1/employee/chat/channels/${id}/messages`, { method: "POST", body: JSON.stringify({ body: clean, replyToId: replyTo?.id, clientId: crypto.randomUUID() }) }); setMessages((current) => [...current, created]); cursor.current = created.createdAt; setReplyTo(null); setNotice(null); } catch (error) { setBody(clean); setNotice(error instanceof Error ? error.message : "Message was not sent."); } }
  async function remove(message: Message) { try { const updated = await request<Message>(`/api/v1/employee/chat/messages/${message.id}`, { method: "DELETE" }); setMessages((current) => current.map((item) => item.id === updated.id ? updated : item)); } catch (error) { setNotice(error instanceof Error ? error.message : "Message was not deleted."); } }
  async function typing(value: string) { setBody(value); if (id && value) void request("/api/v1/employee/chat/presence", { method: "POST", body: JSON.stringify({ status: "online", typingChannelId: id }) }).catch(() => undefined); }
  if (!channel) return <Screen title="Conversation"><StateCard title="Conversation unavailable" body="It may have been deleted, archived, or removed from your membership. No resource details were disclosed." /></Screen>;
  return <Screen eyebrow={channel.kind.toUpperCase()} title={channel.name} refresh={() => void load(true)} refreshing={loading}><View style={styles.searchRow}><TextInput value={search} onChangeText={setSearch} onSubmitEditing={() => { cursor.current = null; void load(true); }} placeholder="Search this conversation" style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.line, color: colors.ink }]} /><Pressable onPress={() => { cursor.current = null; void load(true); }}><Text style={{ color: colors.brand, fontWeight: "900" }}>Search</Text></Pressable></View>{notice ? <StateCard title="Connection notice" body={notice} action="Retry" onAction={() => void load(true)} /> : null}{messages.length ? messages.map((message) => <Card key={message.id}><View style={styles.messageHeader}><Text style={{ color: colors.ink, fontWeight: "900" }}>{message.authorName}</Text><Text style={{ color: colors.muted, fontSize: 11 }}>{new Date(message.createdAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</Text></View><Text style={{ color: message.deletedAt ? colors.muted : colors.ink, fontStyle: message.deletedAt ? "italic" : "normal", lineHeight: 20 }}>{message.deletedAt ? "Message deleted" : message.body}</Text>{message.editedAt ? <Text style={{ color: colors.muted, fontSize: 10 }}>edited</Text> : null}{!message.deletedAt ? <View style={styles.messageActions}><Pressable onPress={() => setReplyTo(message)}><Text style={{ color: colors.brand, fontWeight: "800" }}>Reply</Text></Pressable>{message.authorClerkId === employee.data?.viewer.id || employee.has("chat:moderate") ? <Pressable onPress={() => void remove(message)}><Text style={{ color: colors.danger, fontWeight: "800" }}>Delete</Text></Pressable> : null}</View> : null}</Card>) : !loading && !notice ? <StateCard title="Start the conversation" body="Messages will appear here in near real time. The app reconnects with cursor-based deduplication after interruptions." /> : null}{replyTo ? <View style={[styles.reply, { backgroundColor: colors.brandSoft }]}><Text numberOfLines={1} style={{ color: colors.ink, flex: 1 }}>Replying to {replyTo.authorName}: {replyTo.body}</Text><Pressable onPress={() => setReplyTo(null)}><Text style={{ color: colors.danger, fontWeight: "900" }}>Cancel</Text></Pressable></View> : null}<View style={styles.composer}><TextInput accessibilityLabel="Message" multiline value={body} onChangeText={(value) => void typing(value)} placeholder="Message your team" style={[styles.input, { backgroundColor: colors.surface, borderColor: colors.line, color: colors.ink }]} /><Pressable disabled={!body.trim()} onPress={() => void send()} style={[styles.send, { backgroundColor: colors.brand }, !body.trim() && { opacity: 0.4 }]}><Text style={{ color: colors.onBrand, fontWeight: "900" }}>Send</Text></Pressable></View></Screen>;
}
const styles = StyleSheet.create({ searchRow: { flexDirection: "row", alignItems: "center", gap: 12 }, search: { flex: 1, minHeight: 44, borderWidth: 1, borderRadius: 8, paddingHorizontal: 12 }, messageHeader: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, messageActions: { flexDirection: "row", gap: 18, marginTop: 4 }, reply: { padding: 10, borderRadius: 8, flexDirection: "row", gap: 10 }, composer: { flexDirection: "row", alignItems: "flex-end", gap: 8, paddingVertical: 6 }, input: { flex: 1, minHeight: 48, maxHeight: 130, borderWidth: 1, borderRadius: 10, padding: 12 }, send: { minHeight: 48, borderRadius: 10, paddingHorizontal: 18, alignItems: "center", justifyContent: "center" } });
