"use client";
/* Media URLs are administrator-provided and can predate the configured Image host allowlist. */
/* eslint-disable @next/next/no-img-element */
import { upload } from "@vercel/blob/client";
import { useEffect, useRef, useState } from "react";
import { ArchiveRestore, FileAudio, FileText, FileVideo2, Grid2X2, ImageIcon, List, LoaderCircle, Search, Trash2, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Asset = { id:string;blobUrl:string;filename:string;mimeType:string;size:number;width:number|null;height:number|null;durationMs:number|null;altText:string|null;credit:string|null;copyright:string|null;license:string|null;processingStatus:string;visibility:string;source:string;usageCount:number;usages:Array<{id:string;product:string;ownerType:string;ownerId:string;field:string}>;deletedAt:string|null;createdAt:string;uploadedBySnapshot:{name?:string}|null };
type Payload={data?:Asset[];meta?:{total:number;page:number;pageSize:number};error?:{message?:string}};
export function MediaLibrary() {
  const inputRef=useRef<HTMLInputElement>(null);const [assets,setAssets]=useState<Asset[]>([]);const [total,setTotal]=useState(0);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [view,setView]=useState<"grid"|"table">("grid");
  const [filters,setFilters]=useState({q:"",type:"all",status:"all",usage:"all",deleted:"active",sort:"createdAt",direction:"desc",page:"1",pageSize:"24"});
  async function load(){setBusy(true);const query=new URLSearchParams(filters);const response=await fetch(`/api/v1/studio/media?${query}`);const payload=await response.json() as Payload;if(response.ok){setAssets(payload.data??[]);setTotal(payload.meta?.total??0);}else setMessage(payload.error?.message||"Media could not be loaded.");setBusy(false);}
  useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer);},[filters]); // eslint-disable-line react-hooks/exhaustive-deps
  async function uploadFiles(files:FileList){setBusy(true);setMessage("");for(const file of [...files]){try{const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());const sha256=[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,"0")).join("");await upload(`media/${file.name}`,file,{access:"public",handleUploadUrl:"/api/v1/studio/media/client-upload",clientPayload:JSON.stringify({filename:file.name,sha256,source:"media-library"})});}catch(error){setMessage(error instanceof Error?error.message:`${file.name} could not be uploaded.`);}}setMessage((current)=>current||"Upload completed. Processing metadata may continue in the background.");await load();setBusy(false);}
  async function action(asset:Asset,next:"soft_delete"|"restore"){const response=await fetch("/api/v1/studio/media",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:asset.id,action:next})});const payload=await response.json() as {error?:{message?:string}};setMessage(response.ok?(next==="restore"?"Asset restored.":"Asset moved to Trash."):payload.error?.message||"Media update failed.");await load();}
  async function permanentDelete(asset:Asset){if(!confirm(`Permanently delete ${asset.filename}? This cannot be undone.`))return;const confirmation=prompt(`Type the exact filename to confirm:\\n${asset.filename}`);if(confirmation!==asset.filename){setMessage("Permanent deletion cancelled because the filename did not match.");return;}const response=await fetch(`/api/v1/studio/media?id=${encodeURIComponent(asset.id)}`,{method:"DELETE"});const payload=await response.json() as {error?:{message?:string}};setMessage(response.ok?"Asset permanently deleted and audited.":payload.error?.message||"Permanent deletion failed.");await load();}
  return <div><input ref={inputRef} type="file" multiple className="sr-only" accept="image/*,video/*,audio/*,.vtt,.pdf" onChange={(event)=>{if(event.target.files)void uploadFiles(event.target.files);event.target.value="";}}/><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight">Media library</h1><p className="mt-1 text-sm text-muted-foreground">Every uploaded asset, technical state, source and tracked usage across Courier products.</p></div><Button onClick={()=>inputRef.current?.click()} disabled={busy}>{busy?<LoaderCircle className="animate-spin"/>:<Upload/>} Upload media</Button></div>
  <Card className="mt-7"><CardContent className="grid gap-3 p-4 lg:grid-cols-[minmax(14rem,1fr)_repeat(5,10rem)_auto]"><Label className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search filename…" value={filters.q} onChange={(e)=>setFilters({...filters,q:e.target.value,page:"1"})}/></Label><Filter value={filters.type} change={(type)=>setFilters({...filters,type,page:"1"})} values={["all","image","video","audio","document"]}/><Filter value={filters.status} change={(status)=>setFilters({...filters,status,page:"1"})} values={["all","ready","uploaded","processing","failed"]}/><Filter value={filters.usage} change={(usage)=>setFilters({...filters,usage,page:"1"})} values={["all","used","orphaned"]}/><Filter value={filters.deleted} change={(deleted)=>setFilters({...filters,deleted,page:"1"})} values={["active","deleted","all"]}/><Filter value={filters.sort} change={(sort)=>setFilters({...filters,sort})} values={["createdAt","filename","size","mimeType","usage"]}/><div className="flex"><Button variant={view==="grid"?"secondary":"ghost"} size="icon" onClick={()=>setView("grid")} aria-label="Grid view"><Grid2X2/></Button><Button variant={view==="table"?"secondary":"ghost"} size="icon" onClick={()=>setView("table")} aria-label="Table view"><List/></Button></div></CardContent></Card>
  {message?<p className="my-4 rounded-md border p-3 text-sm" role="status">{message}</p>:null}
  {view==="grid"?<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{assets.map((asset)=><AssetCard key={asset.id} asset={asset} action={action} permanentDelete={permanentDelete}/>)}</div>:<div className="mt-5 overflow-x-auto rounded-md border"><table className="w-full text-sm"><thead><tr className="border-b bg-muted/40 text-left"><th className="p-3">File</th><th>Type</th><th>Size</th><th>Usage</th><th>Status</th><th>Uploaded</th><th/></tr></thead><tbody>{assets.map((asset)=><tr key={asset.id} className="border-b"><td className="p-3"><a href={asset.blobUrl} target="_blank" rel="noreferrer" className="font-semibold hover:underline">{asset.filename}</a><small className="block text-muted-foreground">{asset.source}</small></td><td>{asset.mimeType}</td><td>{formatBytes(asset.size)}</td><td><span>{asset.usageCount}</span>{asset.usages.slice(0,2).map((usage)=><small className="block text-muted-foreground" key={usage.id}>{usage.product} · {usage.ownerType}.{usage.field}</small>)}</td><td>{asset.processingStatus}</td><td>{new Date(asset.createdAt).toLocaleDateString()}</td><td><Action asset={asset} action={action} permanentDelete={permanentDelete}/></td></tr>)}</tbody></table></div>}
  {!assets.length&&!busy?<div className="mt-5 grid min-h-72 place-items-center rounded-lg border border-dashed"><div className="text-center"><ImageIcon className="mx-auto text-muted-foreground"/><h2 className="mt-3 font-semibold">No matching media</h2><p className="text-sm text-muted-foreground">Upload a real asset or change the filters.</p></div></div>:null}
  <div className="mt-5 flex items-center justify-between"><p className="text-xs text-muted-foreground">{total.toLocaleString()} matching database records</p><div className="flex gap-2"><Button variant="outline" disabled={Number(filters.page)<=1} onClick={()=>setFilters({...filters,page:String(Number(filters.page)-1)})}>Previous</Button><Button variant="outline" disabled={Number(filters.page)*Number(filters.pageSize)>=total} onClick={()=>setFilters({...filters,page:String(Number(filters.page)+1)})}>Next</Button></div></div></div>;
}
function AssetCard({asset,action,permanentDelete}:{asset:Asset;action:(asset:Asset,next:"soft_delete"|"restore")=>Promise<void>;permanentDelete:(asset:Asset)=>Promise<void>}){return <Card className="overflow-hidden"><div className="relative grid aspect-video place-items-center bg-muted">{asset.mimeType.startsWith("image/")?<img src={asset.blobUrl} alt={asset.altText||""} className="size-full object-cover"/>:asset.mimeType.startsWith("video/")?<FileVideo2/>:asset.mimeType.startsWith("audio/")?<FileAudio/>:<FileText/>}<span className="absolute right-2 top-2 rounded bg-background/90 px-2 py-1 text-[.6rem] font-bold">{asset.processingStatus}</span></div><CardContent className="p-4"><p className="truncate font-semibold" title={asset.filename}>{asset.filename}</p><p className="mt-1 text-xs text-muted-foreground">{formatBytes(asset.size)} · {asset.usageCount} use{asset.usageCount===1?"":"s"}</p>{asset.usages.slice(0,2).map((usage)=><p className="mt-1 truncate text-[.65rem] text-muted-foreground" key={usage.id}>{usage.product} · {usage.ownerType}.{usage.field}</p>)}<p className="mt-1 text-[.65rem] text-muted-foreground">{asset.uploadedBySnapshot?.name||"Unknown uploader"} · {new Date(asset.createdAt).toLocaleDateString()}</p><Action asset={asset} action={action} permanentDelete={permanentDelete}/></CardContent></Card>;}
function Action({asset,action,permanentDelete}:{asset:Asset;action:(asset:Asset,next:"soft_delete"|"restore")=>Promise<void>;permanentDelete:(asset:Asset)=>Promise<void>}){return asset.deletedAt?<div className="flex flex-wrap"><Button variant="ghost" size="sm" className="mt-2" onClick={()=>void action(asset,"restore")}><ArchiveRestore/> Restore</Button><Button variant="ghost" size="sm" className="mt-2 text-destructive" disabled={asset.usageCount>0} title={asset.usageCount>0?"Remove every tracked usage first":undefined} onClick={()=>void permanentDelete(asset)}><Trash2/> Delete forever</Button></div>:<Button variant="ghost" size="sm" className="mt-2 text-destructive" onClick={()=>void action(asset,"soft_delete")}><Trash2/> Trash</Button>;}
function Filter({value,change,values}:{value:string;change:(value:string)=>void;values:string[]}){return <Select value={value} onValueChange={change}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{values.map(value=><SelectItem key={value} value={value} className="capitalize">{value}</SelectItem>)}</SelectContent></Select>;}function formatBytes(value:number){if(!value)return"Processing";const units=["B","KB","MB","GB"];const index=Math.min(Math.floor(Math.log(value)/Math.log(1024)),3);return`${(value/1024**index).toFixed(index?1:0)} ${units[index]}`;}
