"use client";
import { useEffect, useMemo, useState } from "react";
import { Archive, ExternalLink, Library, LoaderCircle, Save, Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import {
  GuidedEntityMultiPicker,
  GuidedEntityPicker,
} from "@/components/studio/guided-selectors";
import { EditableList } from "@/components/studio/editable-list";
import { premiumContentInput, premiumContentKinds, premiumContentStatuses, premiumKindLabel, premiumPaywallPolicies, type PremiumContentInput, type PremiumContentRecord } from "@/lib/njc-plus-contract";
import type { NjcPlusEditorOptions } from "@/lib/njc-plus-studio-options";

type Form = PremiumContentInput;
const empty: Form = { kind: "article", status: "draft", slug: "", title: "", eyebrow: "NJC+ Original", summary: "", body: [], authors: [], speakers: [], categories: [], tags: [], relatedIds: [], paywallPolicy: "njc_plus", requiredTierIds: [], previewSeconds: 0, commentsEnabled: false, isLive: false, isBreaking: false, isFeatured: false, noIndex: false };

export function NjcPlusContentEditor({ initial, canPublish, options }: { initial?: PremiumContentRecord; canPublish: boolean; options: NjcPlusEditorOptions }) {
  const router = useRouter();
  const draftKey = `njc-plus-editor-${initial?.id ?? "new"}`;
  const [form, setForm] = useState<Form>(() => initial ? fromRecord(initial) : empty);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [autosaveAt, setAutosaveAt] = useState<Date | null>(null);
  const previewHref = initial ? `/plus/${form.slug}?preview=studio` : null;
  const generatedSlug = useMemo(() => slugify(form.title), [form.title]);

  useEffect(() => {
    if (initial) return;
    const timer = setTimeout(() => {
      try { const saved = localStorage.getItem(draftKey); if (saved) setForm(JSON.parse(saved) as Form); } catch { /* Invalid local recovery data is ignored. */ }
    }, 0);
    return () => clearTimeout(timer);
  // This recovery only runs once for this editor identity.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => {
    const timer = setTimeout(() => { try { localStorage.setItem(draftKey, JSON.stringify(form)); setAutosaveAt(new Date()); } catch { /* Browser storage may be unavailable. */ } }, 1_000);
    return () => clearTimeout(timer);
  }, [draftKey, form]);

  function patch<K extends keyof Form>(key: K, value: Form[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function save() {
    setBusy(true); setMessage("");
    const response = await fetch(initial ? `/api/v1/studio/njc-plus/content/${initial.id}` : "/api/v1/studio/njc-plus/content", { method: initial ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
    const payload = await response.json() as { data?: PremiumContentRecord; error?: { message?: string; details?: unknown } };
    if (!response.ok || !payload.data) { setMessage(payload.error?.message || "The NJC+ production could not be saved."); setBusy(false); return; }
    localStorage.removeItem(draftKey);
    setMessage("Saved with a new revision and audit event.");
    if (!initial) router.replace(`/studio/njc-plus/content/${payload.data.id}`);
    router.refresh(); setBusy(false);
  }
  return <div className="grid gap-6 xl:grid-cols-[1fr_22rem]"><div className="space-y-6"><Card><CardHeader><CardTitle>Production identity</CardTitle><CardDescription>One model supports every editorial and media format.</CardDescription></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="Format"><Select value={form.kind} onValueChange={(value) => patch("kind", value as Form["kind"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{premiumContentKinds.map((kind) => <SelectItem key={kind} value={kind}>{premiumKindLabel(kind)}</SelectItem>)}</SelectContent></Select></Field><Field label="Workflow status"><Select value={form.status} onValueChange={(value) => patch("status", value as Form["status"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{premiumContentStatuses.map((status) => <SelectItem key={status} value={status} disabled={!canPublish && ["approved","scheduled","published"].includes(status)} className="capitalize">{status}</SelectItem>)}</SelectContent></Select></Field><Field label="Title" className="sm:col-span-2"><Input value={form.title} onChange={(event) => { patch("title", event.target.value); if (!initial && (!form.slug || form.slug === generatedSlug)) patch("slug", slugify(event.target.value)); }} maxLength={240} /></Field><Field label="URL slug"><Input value={form.slug} onChange={(event) => patch("slug", slugify(event.target.value))} className="font-mono" /></Field><Field label="Eyebrow"><Input value={form.eyebrow} onChange={(event) => patch("eyebrow", event.target.value)} /></Field><Field label="Scheduled publish"><Input type="datetime-local" value={toLocalDateTime(form.scheduledAt)} onChange={(event) => patch("scheduledAt", event.target.value ? new Date(event.target.value).toISOString() : null)} /></Field><Field label="Summary" className="sm:col-span-2"><Textarea value={form.summary} onChange={(event) => patch("summary", event.target.value)} rows={4} maxLength={600} /></Field></CardContent></Card>
    <Card><CardHeader><CardTitle>Credits & relationships</CardTitle><CardDescription>Reuse the same hierarchy for shows, seasons, episodes, podcasts, collections and related reporting.</CardDescription></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="Parent production"><GuidedEntityPicker label="Parent production" value={form.parentId ?? null} options={options.content} onChange={(parentId) => patch("parentId", parentId)} placeholder="No parent production" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Season"><Input type="number" min={0} value={form.seasonNumber ?? ""} onChange={(event) => patch("seasonNumber", event.target.value ? Number(event.target.value) : null)} /></Field><Field label="Episode"><Input type="number" min={0} value={form.episodeNumber ?? ""} onChange={(event) => patch("episodeNumber", event.target.value ? Number(event.target.value) : null)} /></Field></div><Field label="Authors"><EditableList values={form.authors.map((author) => author.name)} onChange={(values) => patch("authors", values.map((name) => ({ name })))} placeholder="Add an author" /></Field><Field label="Hosts / speakers"><EditableList values={form.speakers.map((speaker) => speaker.name)} onChange={(values) => patch("speakers", values.map((name) => ({ name })))} placeholder="Add a host or speaker" /></Field><Field label="Related productions" className="sm:col-span-2"><GuidedEntityMultiPicker label="Related productions" values={form.relatedIds} options={options.content} onChange={(relatedIds) => patch("relatedIds", relatedIds)} placeholder="No related productions" /></Field></CardContent></Card>
    <Card><CardHeader><CardTitle>Story & transcript</CardTitle><CardDescription>Paragraphs are separated by a blank line. Transcripts are indexed only when public search is enabled.</CardDescription></CardHeader><CardContent className="space-y-5"><Field label="Article / supporting copy"><Textarea value={form.body.join("\n\n")} onChange={(event) => patch("body", event.target.value.split(/\n{2,}/).map((item) => item.trim()).filter(Boolean))} rows={14} /></Field><Field label="Accessible transcript"><Textarea value={form.transcript ?? ""} onChange={(event) => patch("transcript", event.target.value || null)} rows={12} /></Field></CardContent></Card>
    <Card><CardHeader><div className="flex items-center justify-between gap-4"><div><CardTitle>Media</CardTitle><CardDescription>Choose Blob-backed assets from the central library. Their URL and media metadata populate automatically.</CardDescription></div><Button variant="outline" size="sm" asChild><a href="/studio/media" target="_blank"><Library /> Media library</a></Button></div></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="Poster / lead image"><GuidedEntityPicker label="Poster or lead image" value={form.imageAssetId ?? null} options={options.images} onChange={(imageAssetId) => { const asset = options.images.find((item) => item.value === imageAssetId); setForm((current) => ({ ...current, imageAssetId, imageUrl: typeof asset?.metadata?.url === "string" ? asset.metadata.url : null, imageAlt: current.imageAlt || (typeof asset?.metadata?.altText === "string" ? asset.metadata.altText : null) })); }} placeholder="Choose an image from Media" /></Field><Field label="Image alt text"><Input value={form.imageAlt ?? ""} onChange={(event) => patch("imageAlt", event.target.value || null)} /></Field><Field label="Video or audio asset"><GuidedEntityPicker label="Video or audio asset" value={form.mediaAssetId ?? null} options={options.media} onChange={(mediaAssetId) => { const asset = options.media.find((item) => item.value === mediaAssetId); setForm((current) => ({ ...current, mediaAssetId, mediaUrl: typeof asset?.metadata?.url === "string" ? asset.metadata.url : null, mediaMimeType: typeof asset?.metadata?.mimeType === "string" ? asset.metadata.mimeType : null, durationMs: typeof asset?.metadata?.durationMs === "number" ? asset.metadata.durationMs : current.durationMs })); }} placeholder="Choose video or audio from Media" /></Field><Field label="Captions URL"><Input value={form.captionsUrl ?? ""} onChange={(event) => patch("captionsUrl", event.target.value || null)} /></Field><Field label="Duration (minutes)"><Input type="number" min={0} value={form.durationMs ? form.durationMs / 60_000 : ""} onChange={(event) => patch("durationMs", event.target.value ? Math.round(Number(event.target.value) * 60_000) : null)} /></Field></CardContent></Card>
    <Card><CardHeader><CardTitle>Access & discovery</CardTitle><CardDescription>Policy is enforced server-side. Public lock treatments never reveal protected media URLs.</CardDescription></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="Paywall policy"><Select value={form.paywallPolicy} onValueChange={(value) => patch("paywallPolicy", value as Form["paywallPolicy"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{premiumPaywallPolicies.map((policy) => <SelectItem key={policy} value={policy}>{policy.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></Field><Field label="Required tiers"><GuidedEntityMultiPicker label="Required NJC+ tiers" values={form.requiredTierIds} options={options.tiers} onChange={(requiredTierIds) => patch("requiredTierIds", requiredTierIds)} placeholder="No specific tier required" /></Field><Field label="Preview seconds"><Input type="number" min={0} value={form.previewSeconds} onChange={(event) => patch("previewSeconds", Math.max(0, Number(event.target.value)))} /></Field><Field label="Rental hours"><Input type="number" min={1} value={form.rentalHours ?? ""} onChange={(event) => patch("rentalHours", event.target.value ? Number(event.target.value) : null)} /></Field><Field label="Tags"><EditableList values={form.tags} onChange={(tags) => patch("tags", tags)} placeholder="Add a discovery tag" /></Field><Field label="Categories"><EditableList values={form.categories} onChange={(categories) => patch("categories", categories)} placeholder="Add a category" /></Field><Field label="SEO title"><Input value={form.seoTitle ?? ""} onChange={(event) => patch("seoTitle", event.target.value || null)} /></Field><Field label="Social image URL"><Input value={form.socialImageUrl ?? ""} onChange={(event) => patch("socialImageUrl", event.target.value || null)} /></Field><Field label="Search description" className="sm:col-span-2"><Textarea value={form.seoDescription ?? ""} onChange={(event) => patch("seoDescription", event.target.value || null)} rows={3} /></Field><Toggle label="Featured" checked={form.isFeatured} onChange={(value) => patch("isFeatured", value)} /><Toggle label="Breaking treatment" checked={form.isBreaking} onChange={(value) => patch("isBreaking", value)} /><Toggle label="Live now" checked={form.isLive} onChange={(value) => patch("isLive", value)} /><Toggle label="Comments eligible" checked={form.commentsEnabled} onChange={(value) => patch("commentsEnabled", value)} /><Toggle label="Keep out of search" checked={form.noIndex} onChange={(value) => patch("noIndex", value)} /></CardContent></Card></div>
    <aside><Card className="sticky top-20"><CardHeader><Sparkles className="size-5 text-primary" /><CardTitle>Production controls</CardTitle><CardDescription>Browser recovery autosaves locally. Server saves create immutable revisions.</CardDescription></CardHeader><CardContent className="space-y-4"><Button className="w-full" onClick={() => void save()} disabled={busy || form.title.length < 3 || form.slug.length < 2}>{busy ? <LoaderCircle className="animate-spin" /> : <Save />} Save production</Button>{previewHref ? <Button variant="outline" className="w-full" asChild><a href={previewHref} target="_blank" rel="noreferrer"><ExternalLink /> Private preview</a></Button> : null}<div className="rounded-md bg-muted p-3 text-xs text-muted-foreground"><p>Recovery {autosaveAt ? `saved at ${autosaveAt.toLocaleTimeString()}` : "waiting for changes"}</p><p className="mt-1">Database status: {initial?.status ?? "not created"}</p></div>{message ? <p className="rounded-md border p-3 text-xs" role="status">{message}</p> : null}{initial ? <Button variant="ghost" className="w-full text-destructive" onClick={async () => { if (!confirm("Archive this NJC+ production?")) return; await fetch(`/api/v1/studio/njc-plus/content/${initial.id}`, { method: "DELETE" }); router.push("/studio/njc-plus/content"); router.refresh(); }}><Archive /> Archive</Button> : null}</CardContent></Card></aside></div>;
}
function Field({ label, children, className = "" }: { label: string; children: React.ReactNode; className?: string }) { return <Label className={`block space-y-2 ${className}`}><span>{label}</span>{children}</Label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <Label className="flex items-center justify-between rounded-md border p-3">{label}<Switch checked={checked} onCheckedChange={onChange} /></Label>; }
function slugify(value: string) { return value.toLowerCase().trim().replace(/['’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 180); }
function toLocalDateTime(value?: string | null) { if (!value) return ""; const date = new Date(value); const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
function fromRecord(record: PremiumContentRecord): Form { return premiumContentInput.parse({ ...record, parentId: record.parentId, seasonNumber: record.seasonNumber, episodeNumber: record.episodeNumber, durationMs: record.durationMs, imageAssetId: record.imageAssetId, imageUrl: record.imageUrl, imageAlt: record.imageAlt, mediaAssetId: record.mediaAssetId, mediaUrl: record.mediaUrl, mediaMimeType: record.mediaMimeType, captionsUrl: record.captionsUrl, transcript: record.transcript, scheduledAt: record.scheduledAt?.toISOString() ?? null, seoTitle: record.seoTitle, seoDescription: record.seoDescription, socialImageUrl: record.socialImageUrl, rentalHours: record.rentalHours }); }
