"use client";
import { useState } from "react";
import { LoaderCircle, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import type { premiumOffers, premiumTiers, accessCreditRedemptionRules } from "@harborline/backend/schema";

type Tier = typeof premiumTiers.$inferSelect; type Offer = typeof premiumOffers.$inferSelect; type Rule = typeof accessCreditRedemptionRules.$inferSelect;
export function NjcPlusCommerce({ tiers: initialTiers, offers: initialOffers, rules, canManage }: { tiers: Tier[]; offers: Offer[]; rules: Rule[]; canManage: boolean }) {
  const [tiers, setTiers] = useState(initialTiers); const [offers, setOffers] = useState(initialOffers); const [creditRules, setCreditRules] = useState(rules); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [tier, setTier] = useState({ resource: "tier", slug: "", name: "", description: "", priceCents: 0, currency: "usd", interval: "month", benefits: [] as string[], capabilities: ["njc_plus"], trialEligible: true, accessCreditEligible: true, available: false, visible: false, providerPriceId: "" });
  const [offer, setOffer] = useState({ resource: "offer", slug: "three-day-dollar", tierId: "", name: "Three-day NJC+ trial", promotionalText: "$1 for three days. Renews at the displayed tier price unless cancelled.", priceCents: 100, durationDays: 3, active: false, perUserLimit: 1, paymentRequired: true, autoRenews: true, renewalPriceCents: null as number | null, providerPriceId: "" });
  const [rule, setRule] = useState({ resource: "credit_rule", name: "", active: false, costCredits: 100, benefitType: "days", benefitValue: 1 as number | null, tierId: null as string | null, contentId: null as string | null });
  async function save(value: object, type: "tier" | "offer" | "credit rule") { setBusy(true); setMessage(""); const response = await fetch("/api/v1/studio/njc-plus/commerce", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(value) }); const payload = await response.json() as { data?: Tier | Offer | Rule; error?: { message?:string } }; if (response.ok && payload.data) { if (type === "tier") setTiers((items) => [...items.filter((item) => item.id !== payload.data!.id), payload.data as Tier]); else if(type === "offer") setOffers((items) => [...items.filter((item) => item.id !== payload.data!.id), payload.data as Offer]); else setCreditRules((items)=>[...items.filter((item)=>item.id!==payload.data!.id),payload.data as Rule]); setMessage(`${type} saved and audited.`); } else setMessage(payload.error?.message || `${type} could not be saved.`); setBusy(false); }
  return <div className="space-y-6"><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Tiers</CardTitle><CardDescription>Multiple reusable tiers are supported even if one is visible at launch.</CardDescription></CardHeader><CardContent><div className="space-y-3">{tiers.map((item) => <button key={item.id} className="flex w-full items-center justify-between rounded-md border p-3 text-left" onClick={() => setTier({ resource:"tier", slug:item.slug,name:item.name,description:item.description,priceCents:item.priceCents,currency:item.currency,interval:item.interval,benefits:item.benefits,capabilities:item.capabilities,trialEligible:item.trialEligible,accessCreditEligible:item.accessCreditEligible,available:item.available,visible:item.visible,providerPriceId:item.providerPriceId ?? "", id:item.id } as never)}><span><strong>{item.name}</strong><small className="block text-muted-foreground">${(item.priceCents/100).toFixed(2)} / {item.interval}</small></span><span className={item.visible ? "text-emerald-500" : "text-muted-foreground"}>{item.visible ? "Visible" : "Hidden"}</span></button>)}</div></CardContent></Card><Card><CardHeader><Plus className="size-5 text-primary" /><CardTitle>Tier editor</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field label="Name"><Input value={tier.name} onChange={(e)=>setTier({...tier,name:e.target.value})}/></Field><Field label="Slug"><Input value={tier.slug} onChange={(e)=>setTier({...tier,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-")})}/></Field><Field label="Price in cents"><Input type="number" value={tier.priceCents} onChange={(e)=>setTier({...tier,priceCents:Number(e.target.value)})}/></Field><Field label="Billing interval"><Input value={tier.interval} onChange={(e)=>setTier({...tier,interval:e.target.value})}/></Field><Field label="Description" className="sm:col-span-2"><Input value={tier.description} onChange={(e)=>setTier({...tier,description:e.target.value})}/></Field><Field label="Benefits, comma-separated" className="sm:col-span-2"><Input value={tier.benefits.join(", ")} onChange={(e)=>setTier({...tier,benefits:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)})}/></Field><Field label="Stripe recurring price ID" className="sm:col-span-2"><Input value={tier.providerPriceId} onChange={(e)=>setTier({...tier,providerPriceId:e.target.value})}/></Field><Toggle label="Available" checked={tier.available} change={(available)=>setTier({...tier,available})}/><Toggle label="Publicly visible" checked={tier.visible} change={(visible)=>setTier({...tier,visible})}/><Button className="sm:col-span-2" disabled={!canManage||busy} onClick={()=>void save(tier,"tier")}>{busy?<LoaderCircle className="animate-spin"/>:"Save tier"}</Button></CardContent></Card></div>
  <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Offers</CardTitle><CardDescription>The required $1 / three-day trial is configurable, limited per user and off by default.</CardDescription></CardHeader><CardContent className="space-y-3">{offers.map((item)=><button key={item.id} className="flex w-full justify-between rounded-md border p-3 text-left" onClick={()=>setOffer({resource:"offer",slug:item.slug,tierId:item.tierId,name:item.name,promotionalText:item.promotionalText,priceCents:item.priceCents,durationDays:item.durationDays,active:item.active,perUserLimit:item.perUserLimit,paymentRequired:item.paymentRequired,autoRenews:item.autoRenews,renewalPriceCents:item.renewalPriceCents,providerPriceId:item.providerPriceId ?? "",id:item.id} as never)}><span><strong>{item.name}</strong><small className="block text-muted-foreground">${(item.priceCents/100).toFixed(2)} · {item.durationDays} days</small></span><span>{item.active?"Active":"Off"}</span></button>)}</CardContent></Card><Card><CardHeader><CardTitle>Trial / promotion editor</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field label="Offer name"><Input value={offer.name} onChange={(e)=>setOffer({...offer,name:e.target.value})}/></Field><Field label="Tier"><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={offer.tierId} onChange={(e)=>setOffer({...offer,tierId:e.target.value})}><option value="">Select tier</option>{tiers.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Price cents"><Input type="number" value={offer.priceCents} onChange={(e)=>setOffer({...offer,priceCents:Number(e.target.value)})}/></Field><Field label="Duration days"><Input type="number" value={offer.durationDays} onChange={(e)=>setOffer({...offer,durationDays:Number(e.target.value)})}/></Field><Field label="Promotion text" className="sm:col-span-2"><Input value={offer.promotionalText} onChange={(e)=>setOffer({...offer,promotionalText:e.target.value})}/></Field><Field label="Stripe one-time price ID" className="sm:col-span-2"><Input value={offer.providerPriceId} onChange={(e)=>setOffer({...offer,providerPriceId:e.target.value})}/></Field><Toggle label="Active" checked={offer.active} change={(active)=>setOffer({...offer,active})}/><Toggle label="Auto-renews" checked={offer.autoRenews} change={(autoRenews)=>setOffer({...offer,autoRenews})}/><Button className="sm:col-span-2" disabled={!canManage||busy||!offer.tierId} onClick={()=>void save(offer,"offer")}>{busy?<LoaderCircle className="animate-spin"/>:"Save offer"}</Button></CardContent></Card></div>
  <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Access Credit redemption rules</CardTitle><CardDescription>{creditRules.length} configurable ledger-backed rule{creditRules.length===1?"":"s"}. Public redemption remains behind its child flag.</CardDescription></CardHeader><CardContent className="space-y-3">{creditRules.map((item)=><button key={item.id} className="flex w-full justify-between rounded-md border p-3 text-left" onClick={()=>setRule({resource:"credit_rule",name:item.name,active:item.active,costCredits:item.costCredits,benefitType:item.benefitType,benefitValue:item.benefitValue,tierId:item.tierId,contentId:item.contentId,id:item.id} as never)}><span><strong>{item.name}</strong><small className="block text-muted-foreground">{item.costCredits} credits · {item.benefitType.replaceAll("_"," ")}</small></span><span>{item.active?"Active":"Off"}</span></button>)}</CardContent></Card><Card><CardHeader><CardTitle>Redemption rule editor</CardTitle><CardDescription>Conversion values are data, never hard-coded into the app.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field label="Rule name"><Input value={rule.name} onChange={(e)=>setRule({...rule,name:e.target.value})}/></Field><Field label="Credit cost"><Input type="number" min={1} value={rule.costCredits} onChange={(e)=>setRule({...rule,costCredits:Number(e.target.value)})}/></Field><Field label="Benefit type"><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={rule.benefitType} onChange={(e)=>setRule({...rule,benefitType:e.target.value})}>{["days","weeks","months","tier_upgrade","content_unlock","rental"].map(value=><option value={value} key={value}>{value.replaceAll("_"," ")}</option>)}</select></Field><Field label="Benefit amount"><Input type="number" min={1} value={rule.benefitValue??""} onChange={(e)=>setRule({...rule,benefitValue:e.target.value?Number(e.target.value):null})}/></Field><Field label="Tier ID (when needed)" className="sm:col-span-2"><Input value={rule.tierId??""} onChange={(e)=>setRule({...rule,tierId:e.target.value||null})}/></Field><Field label="Content ID (when needed)" className="sm:col-span-2"><Input value={rule.contentId??""} onChange={(e)=>setRule({...rule,contentId:e.target.value||null})}/></Field><Toggle label="Active" checked={rule.active} change={(active)=>setRule({...rule,active})}/><Button disabled={!canManage||busy||rule.name.length<2} onClick={()=>void save(rule,"credit rule")}>{busy?<LoaderCircle className="animate-spin"/>:"Save rule"}</Button></CardContent></Card></div>{message?<p role="status" className="text-sm">{message}</p>:null}</div>;
}
function Field({label,children,className=""}:{label:string;children:React.ReactNode;className?:string}){return <Label className={`block space-y-2 ${className}`}><span>{label}</span>{children}</Label>;} function Toggle({label,checked,change}:{label:string;checked:boolean;change:(value:boolean)=>void}){return <Label className="flex items-center justify-between rounded-md border p-3">{label}<Switch checked={checked} onCheckedChange={change}/></Label>;}
