import type { Story, WeatherSnapshot } from "@harborline/contracts";

const authors = {
  ariana: { id: "author-ariana-patel", name: "Ariana Patel", role: "Middlesex County reporter", initials: "AP" },
  marcus: { id: "author-marcus-green", name: "Marcus Green", role: "Statehouse editor", initials: "MG" },
  elena: { id: "author-elena-torres", name: "Elena Torres", role: "Community editor", initials: "ET" },
  david: { id: "author-david-kim", name: "David Kim", role: "High school sports editor", initials: "DK" },
  forum: { id: "garden-state-forum", name: "Garden State Forum", role: "Opinion desk", initials: "GF" },
};

export const seedStories: Story[] = [
  {
    id: "story-transit-corridor",
    slug: "middlesex-transit-corridor-plan-enters-public-review",
    headline: "Middlesex transit corridor plan enters public review across five towns",
    dek: "The proposal connects bus priority, safer crossings and new station links from New Brunswick to the Route 1 employment corridor.",
    body: [
      "MIDDLESEX COUNTY — County planners have opened a 45-day public review of a proposed transit corridor linking New Brunswick, North Brunswick, South Brunswick, Plainsboro and East Brunswick.",
      "The draft combines bus-priority lanes, redesigned intersections and improved connections to rail stations. Evening meetings are planned in each community before the county issues a final recommendation.",
      "This launch-preview article is fictional sample content created to demonstrate The New Jersey Courier’s county reporting format. It is not a report of an actual pending project.",
    ],
    category: "middlesex",
    categoryLabel: "Middlesex County",
    location: "New Brunswick",
    publishedAt: "2026-07-14T13:25:00-04:00",
    updatedAt: "2026-07-14T14:05:00-04:00",
    readingMinutes: 6,
    image: "/assets/editorial/v1/garden-state-engraving.png",
    imageAlt: "An original engraved illustration of New Jersey with civic and county linework",
    author: authors.ariana,
    tags: ["transit", "Route 1", "New Brunswick", "county government"],
    status: "published",
    isDeveloping: true,
  },
  {
    id: "story-school-facilities",
    slug: "edison-school-facilities-hearings-begin-this-week",
    headline: "Edison school facilities hearings begin this week",
    dek: "Residents will get their first detailed look at enrollment assumptions and renovation priorities.",
    body: ["EDISON — The school board will hold two public workshops this week on a fictional facilities proposal included for launch demonstration purposes."],
    category: "middlesex",
    categoryLabel: "Edison",
    location: "Edison",
    publishedAt: "2026-07-14T11:42:00-04:00",
    readingMinutes: 4,
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "Students walking through a school courtyard",
    author: authors.elena,
    tags: ["schools", "Edison", "facilities"],
    status: "published",
  },
  {
    id: "story-state-budget",
    slug: "what-the-state-budget-means-for-middlesex-property-tax-relief",
    headline: "What the state budget could mean for Middlesex property-tax relief",
    dek: "A line-by-line Courier explainer tracks the programs most likely to reach local households and municipalities.",
    body: ["TRENTON — This sample explainer demonstrates how the Statehouse Desk will translate statewide decisions into county-level consequences."],
    category: "statehouse",
    categoryLabel: "Statehouse Desk",
    location: "Trenton",
    publishedAt: "2026-07-14T10:10:00-04:00",
    readingMinutes: 7,
    image: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "A domed government building beneath a blue sky",
    author: authors.marcus,
    tags: ["Statehouse", "budget", "property taxes"],
    status: "published",
    isExclusive: true,
  },
  {
    id: "story-weekly-pulse",
    slug: "weekly-pulse-route-9-redevelopment-priorities",
    headline: "Weekly Pulse: What should lead the next Route 9 redevelopment plan?",
    dek: "Housing, traffic safety, small businesses or open space: Middlesex residents set this week’s public agenda.",
    body: ["The Weekly Pulse is a reader-engagement demonstration. Results are non-scientific and will be paired with methodology and expert context."],
    category: "public-square",
    categoryLabel: "The Weekly Pulse",
    location: "Middlesex County",
    publishedAt: "2026-07-14T09:15:00-04:00",
    readingMinutes: 3,
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "Community members gathered around a table",
    author: authors.elena,
    tags: ["poll", "Route 9", "public square"],
    status: "published",
    isLive: true,
  },
  {
    id: "story-player-week",
    slug: "vote-middlesex-player-of-the-week-opening-ballot",
    headline: "Vote: Middlesex Player of the Week opening ballot",
    dek: "Six standout performances across baseball, softball, track and lacrosse make the first reader ballot.",
    body: ["This fictional ballot previews the Courier’s planned high-school sports voting experience. Player details will require school confirmation and appropriate permissions before launch."],
    category: "sports",
    categoryLabel: "Jersey Gridiron & Court",
    location: "Middlesex County",
    publishedAt: "2026-07-13T20:30:00-04:00",
    readingMinutes: 4,
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "Runners competing on an outdoor track",
    author: authors.david,
    tags: ["high school sports", "player of the week", "voting"],
    status: "published",
  },
  {
    id: "story-opinion-downtowns",
    slug: "garden-state-forum-small-downtowns-need-patient-growth",
    headline: "Our small downtowns need patient growth, not one-size-fits-all fixes",
    dek: "A local business owner argues that municipal plans should protect the character that makes each borough useful and distinct.",
    body: ["The Garden State Forum will publish clearly labeled opinion from residents with relevant experience, disclose conflicts and separate commentary from reported news."],
    category: "opinion",
    categoryLabel: "Garden State Forum",
    location: "Metuchen",
    publishedAt: "2026-07-13T17:10:00-04:00",
    readingMinutes: 5,
    image: "https://images.unsplash.com/photo-1514924013411-cbf25faa35bb?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "A walkable downtown street with local storefronts",
    author: authors.forum,
    tags: ["opinion", "downtowns", "small business"],
    status: "published",
  },
  {
    id: "story-water-testing",
    slug: "how-middlesex-towns-publish-drinking-water-tests",
    headline: "How every Middlesex town publishes its drinking-water tests",
    dek: "The Courier reviewed where residents can find reports, how often they are updated and what the numbers mean.",
    body: ["This sample accountability story demonstrates the service-journalism format planned for county data and public records."],
    category: "investigates",
    categoryLabel: "Courier Watch",
    location: "Middlesex County",
    publishedAt: "2026-07-13T14:40:00-04:00",
    readingMinutes: 8,
    image: "https://images.unsplash.com/photo-1538300342682-cf57afb97285?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "Clear water running from a household faucet",
    author: authors.ariana,
    tags: ["water", "public records", "accountability"],
    status: "published",
  },
  {
    id: "story-laurels",
    slug: "jersey-laurels-nominations-open-for-community-service",
    headline: "Jersey Laurels nominations open for community service",
    dek: "Readers can recognize the neighbors, educators and local organizations whose work rarely makes a headline.",
    body: ["The Jersey Laurels preview uses a moderated nomination workflow with published eligibility, judging and sponsor-disclosure rules."],
    category: "jersey-laurels",
    categoryLabel: "Jersey Laurels",
    location: "Middlesex County",
    publishedAt: "2026-07-13T12:00:00-04:00",
    readingMinutes: 3,
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=84",
    imageAlt: "Neighbors gathered together outdoors",
    author: authors.elena,
    tags: ["Jersey Laurels", "nominations", "community"],
    status: "published",
  },
];

export const weatherSeed: WeatherSnapshot = {
  location: "New Brunswick",
  temperature: 81,
  feelsLike: 84,
  condition: "Partly cloudy",
  high: 86,
  low: 69,
  wind: "SW 8 mph",
  humidity: 61,
  hourly: [
    { time: "Now", temperature: 81, condition: "Partly cloudy" },
    { time: "5 PM", temperature: 83, condition: "Partly cloudy" },
    { time: "7 PM", temperature: 79, condition: "Clear" },
    { time: "9 PM", temperature: 75, condition: "Clear" },
    { time: "11 PM", temperature: 72, condition: "Clear" },
    { time: "1 AM", temperature: 70, condition: "Clear" },
  ],
};

export const studioDrafts = [
  { id: "draft-1", headline: "Council agenda watch: five meetings this week", section: "Middlesex", owner: "Ariana Patel", status: "review", updated: "8 min ago" },
  { id: "draft-2", headline: "Explainer: Reading your municipal tax bill", section: "Courier Watch", owner: "Marcus Green", status: "draft", updated: "24 min ago" },
  { id: "draft-3", headline: "Friday night football preview", section: "Gridiron & Court", owner: "David Kim", status: "scheduled", updated: "1 hr ago" },
];
